import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { acquireWatcherLock, cycle, isFastForward, readState, resolveGitStateFile, terminalIdentity, validateAuthoritativeCheckout, writeState } from "./pipeline-pilot-watch.mjs";

const temp = fs.mkdtempSync(path.join(os.tmpdir(), "agentops-pipeline-watch-"));
const actualRepo = path.resolve(rootFromImportMeta(import.meta.url), "..", "..");
const root = path.join(temp, ".agentops");
const stateFile = path.join(temp, ".git", "agentops-pipeline", "state.json");
fs.mkdirSync(path.join(root, "work", "AS-1"), { recursive: true });
const capsule = { ticket: "AS-1", lifecycle_state: "resolved", owner_actor: "maker", current_hash: "sha256:aaa" };
fs.writeFileSync(path.join(root, "work", "AS-1", "CURRENT.json"), JSON.stringify(capsule));
assert.match(terminalIdentity(capsule), /^sha256:[a-f0-9]{64}$/);
assert.equal(terminalIdentity({ ...capsule, lifecycle_state: "assigned" }), null);
const actualState = resolveGitStateFile(actualRepo);
assert.match(actualState.replaceAll("\\", "/"), /\.git\/agentops-pipeline\/state\.json$/);
const gitFixture = path.join(temp, "git-fixture");
const linkedFixture = path.join(temp, "git-fixture-linked");
const secondLinkedFixture = path.join(temp, "git-fixture-linked-second");
fs.mkdirSync(gitFixture);
execFileSync("git", ["init", "-q"], { cwd: gitFixture, windowsHide: true });
fs.writeFileSync(path.join(gitFixture, "seed.txt"), "seed\n");
execFileSync("git", ["add", "seed.txt"], { cwd: gitFixture, windowsHide: true });
execFileSync("git", ["-c", "user.name=AgentOps Test", "-c", "user.email=test@example.invalid", "commit", "-qm", "seed"], { cwd: gitFixture, windowsHide: true });
execFileSync("git", ["branch", "-M", "dev"], { cwd: gitFixture, windowsHide: true });
execFileSync("git", ["update-ref", "refs/remotes/origin/dev", "HEAD"], { cwd: gitFixture, windowsHide: true });
const source = validateAuthoritativeCheckout(gitFixture, "dev");
assert.equal(source.head, source.remote);
execFileSync("git", ["worktree", "add", "-q", linkedFixture, "-b", "linked-test"], { cwd: gitFixture, windowsHide: true });
execFileSync("git", ["worktree", "add", "-q", secondLinkedFixture, "-b", "linked-test-second"], { cwd: gitFixture, windowsHide: true });
assert.equal(resolveGitStateFile(linkedFixture), resolveGitStateFile(secondLinkedFixture));
assert.match(resolveGitStateFile(linkedFixture).replaceAll("\\", "/"), /\.git\/agentops-pipeline\/state\.json$/);
assert.throws(() => validateAuthoritativeCheckout(linkedFixture, "dev"), /requires authoritative branch/);
const sharedLock = path.join(path.dirname(resolveGitStateFile(linkedFixture)), "watcher.lock");
const releaseShared = acquireWatcherLock(sharedLock);
assert.throws(() => acquireWatcherLock(path.join(path.dirname(resolveGitStateFile(secondLinkedFixture)), "watcher.lock")), /already active/);
releaseShared();
const baselineState = path.join(temp, ".git", "agentops-pipeline", "baseline.json");
let baselineCalls = 0;
assert.equal(cycle({ root, stateFile: baselineState, now: "2026-08-30T09:59:00Z", initialize: true, offer: () => { baselineCalls++; return { status: "OFFERED" }; } }).status, "QUIET");
assert.equal(baselineCalls, 0);

let calls = 0;
const offered = (_root, args) => { calls++; return { status: "OFFERED", completed_ticket: args.completedTicket, released_actor: args.releasedActor }; };
const driftState = path.join(temp, ".git", "agentops-pipeline", "drift.json");
cycle({ root, stateFile: driftState, now: "2026-08-30T12:00:00Z", initialize: true, sourceHead: source.head, offer: offered });
fs.writeFileSync(path.join(gitFixture, "seed.txt"), "seed\nadvance\n");
execFileSync("git", ["add", "seed.txt"], { cwd: gitFixture, windowsHide: true });
execFileSync("git", ["-c", "user.name=AgentOps Test", "-c", "user.email=test@example.invalid", "commit", "-qm", "advance"], { cwd: gitFixture, windowsHide: true });
execFileSync("git", ["update-ref", "refs/remotes/origin/dev", "HEAD"], { cwd: gitFixture, windowsHide: true });
const advanced = validateAuthoritativeCheckout(gitFixture, "dev");
assert.equal(isFastForward(gitFixture, source.head, advanced.head), true);
const processedBeforeAdvance = [...readState(driftState).processed];
cycle({ root, stateFile: driftState, now: "2026-08-30T12:00:01Z", sourceHead: advanced.head, allowSourceAdvance: true, offer: offered });
assert.deepEqual(readState(driftState).processed, processedBeforeAdvance);
const pendingFfState = path.join(temp, ".git", "agentops-pipeline", "pending-ff.json");
const noSafeAlways = () => ({ status: "NO_SAFE_ASSIGNMENT" });
cycle({ root, stateFile: pendingFfState, now: "2026-08-30T12:01:00Z", sourceHead: source.head, offer: noSafeAlways });
cycle({ root, stateFile: pendingFfState, now: "2026-08-30T12:01:01Z", sourceHead: advanced.head, allowSourceAdvance: true, offer: noSafeAlways });
assert.equal(readState(pendingFfState).pending.length, 1);
const newTerminalFfState = path.join(temp, ".git", "agentops-pipeline", "new-terminal-ff.json");
cycle({ root, stateFile: newTerminalFfState, now: "2026-08-30T12:02:00Z", initialize: true, sourceHead: source.head, offer: offered });
capsule.current_hash = "sha256:ff-advance";
fs.writeFileSync(path.join(root, "work", "AS-1", "CURRENT.json"), JSON.stringify(capsule));
assert.equal(cycle({ root, stateFile: newTerminalFfState, now: "2026-08-30T12:02:01Z", sourceHead: advanced.head, allowSourceAdvance: true, offer: offered }).events.length, 1);
const tree = execFileSync("git", ["rev-parse", "HEAD^{tree}"], { cwd: gitFixture, encoding: "utf8", windowsHide: true }).trim();
const unrelated = execFileSync("git", ["-c", "user.name=AgentOps Test", "-c", "user.email=test@example.invalid", "commit-tree", tree, "-m", "unrelated"], { cwd: gitFixture, encoding: "utf8", windowsHide: true }).trim();
assert.equal(isFastForward(gitFixture, advanced.head, unrelated), false);
assert.throws(() => cycle({ root, stateFile: driftState, now: "2026-08-30T12:00:02Z", sourceHead: unrelated, offer: offered }), /non-fast-forward/);
calls = 0;
assert.equal(cycle({ root, stateFile, now: "2026-08-30T10:00:00Z", offer: offered }).status, "MATERIAL_CHANGE");
assert.equal(calls, 1);
assert.equal(cycle({ root, stateFile, now: "2026-08-30T10:00:01Z", offer: offered }).status, "QUIET");
assert.equal(calls, 1);

capsule.current_hash = "sha256:bbb";
fs.writeFileSync(path.join(root, "work", "AS-1", "CURRENT.json"), JSON.stringify(capsule));
assert.equal(cycle({ root, stateFile, now: "2026-08-30T10:01:00Z", offer: offered }).events.length, 1);
assert.equal(calls, 2);

capsule.current_hash = "sha256:ccc";
fs.writeFileSync(path.join(root, "work", "AS-1", "CURRENT.json"), JSON.stringify(capsule));
const alarmOffer = (_root, args) => ({ status: Date.parse(args.now) - Date.parse(args.releasedAt) >= 300000 ? "IDLE_ALARM" : "NO_SAFE_ASSIGNMENT" });
assert.equal(cycle({ root, stateFile, now: "2026-08-30T11:00:00Z", offer: alarmOffer }).status, "MATERIAL_CHANGE");
assert.equal(readState(stateFile).pending.length, 1);
assert.equal(cycle({ root, stateFile, now: "2026-08-30T11:04:59Z", offer: alarmOffer }).status, "QUIET");
const alarm = cycle({ root, stateFile, now: "2026-08-30T11:05:00Z", offer: alarmOffer });
assert.equal(alarm.events[0].result.status, "IDLE_ALARM");
assert.equal(readState(stateFile).pending.length, 0);
assert.equal(cycle({ root, stateFile, now: "2026-08-30T11:05:01Z", offer: alarmOffer }).events.length, 0);

const before = fs.readFileSync(path.join(root, "work", "AS-1", "CURRENT.json"), "utf8");
const state = readState(stateFile);
state.observations = Array.from({ length: 150 }, (_, i) => ({ i }));
writeState(stateFile, state, 100);
assert.equal(readState(stateFile).observations.length, 100);
assert.equal(fs.readFileSync(path.join(root, "work", "AS-1", "CURRENT.json"), "utf8"), before);
const bulkRoot = path.join(temp, "bulk-agentops");
const bulkState = path.join(temp, ".git", "agentops-pipeline", "bulk.json");
for (let i = 0; i < 120; i++) {
  const ticket = `BULK-${String(i).padStart(3, "0")}`;
  const directory = path.join(bulkRoot, "work", ticket);
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, "CURRENT.json"), JSON.stringify({ ticket, lifecycle_state: "resolved", owner_actor: "maker", current_hash: `sha256:bulk-${i}` }));
}
assert.equal(cycle({ root: bulkRoot, stateFile: bulkState, now: "2026-08-30T13:00:00Z", initialize: true, offer: offered }).status, "QUIET");
assert.equal(readState(bulkState).processed.length, 120);
assert.equal(cycle({ root: bulkRoot, stateFile: bulkState, now: "2026-08-30T13:00:01Z", offer: offered }).events.length, 0);
const changedBulk = path.join(bulkRoot, "work", "BULK-000", "CURRENT.json");
fs.writeFileSync(changedBulk, JSON.stringify({ ticket: "BULK-000", lifecycle_state: "resolved", owner_actor: "maker", current_hash: "sha256:bulk-changed" }));
assert.equal(cycle({ root: bulkRoot, stateFile: bulkState, now: "2026-08-30T13:00:02Z", offer: offered }).events.length, 1);
fs.writeFileSync(changedBulk, JSON.stringify({ ticket: "BULK-000", lifecycle_state: "assigned", owner_actor: "maker", current_hash: "sha256:bulk-assigned" }));
cycle({ root: bulkRoot, stateFile: bulkState, now: "2026-08-30T13:00:03Z", offer: offered });
assert.equal(readState(bulkState).processed.length, 119);
const lockFile = path.join(temp, ".git", "agentops-pipeline", "test.lock");
const release = acquireWatcherLock(lockFile);
assert.throws(() => acquireWatcherLock(lockFile), /already active/);
release();
assert.equal(fs.existsSync(lockFile), false);
console.log("PASS 39/39; terminal-denominator=120; second-scan-replay0; changed-hash-once=yes; removed-terminal-pruned=yes; observations-bounded=100; fast-forward-retains-state=yes; pending-survives-fast-forward=yes; new-terminal-on-fast-forward-once=yes; non-fast-forward-refused=yes; current-dev-accepted=yes; stale-feature-refused=yes; second-linked-watcher-refused=yes; repo-wide-common-state=yes; single-watcher-lock=yes; historical-baseline=yes; stable-terminal-hash=yes; persistent-dedupe=yes; immediate-offer=yes; pending-alarm=yes; alarm-at-300s=yes; duplicate-alarm0; AgentOps-writes=0");

function rootFromImportMeta(url) {
  return new URL(".", url).pathname.replace(/^\/(.:)/, "$1");
}
