import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { atomicWriteJson, commitClaimTransfer, recoverExpiredClaim, sealClaim, sealLease, seatFingerprint, transferClaim, validateLease } from "./pipeline-seat-claims.mjs";
const a="seat:feature-architecture:11111111-1111-4111-8111-111111111111", b="seat:feature-architecture:22222222-2222-4222-8222-222222222222", secret="target-seat-secret-capability-2222222222222222";
const registry={ [b]:{role:"maker",status:"active",capability_fingerprint:seatFingerprint(secret)} };
const claim=sealClaim({schema:"agentops/seat-claim/v1",revision:1,parent_hash:null,ticket:"AS-HD-269",seat_id:a,lease_id:"lease-269",ref:"codex/issue-269",path_globs:["src/feature/**"],issued:"2026-08-30T10:00:00Z",expiry:"2026-08-30T11:00:00Z",status:"active"});
const lease=sealLease({schema:"agentops/seat-lease/v1",revision:1,parent_hash:null,id:"lease-269",actor:"maker",seat_id:a,issuer:"it-manager-iii",ticket:"AS-HD-269",ref:"codex/issue-269",path_globs:["src/feature/**"],issued:"2026-08-30T10:00:00Z",expiry:"2026-08-30T11:00:00Z",revoked:false});
assert.equal(validateLease(lease,claim,"2026-08-30T10:30:00Z"),lease);
const args={claim,lease,expectedHash:claim.current_hash,targetSeat:b,targetCapability:secret,seatRegistry:registry,issuerRole:"it-manager-iii",now:"2026-08-30T10:30:00Z",expiry:"2026-08-30T11:30:00Z"};
const moved=transferClaim(args); assert.equal(moved.claim.seat_id,b); assert.equal(moved.lease.seat_id,b); assert.equal(moved.claim.parent_hash,claim.current_hash); assert.match(moved.event.event_hash,/^sha256:/); assert.equal(JSON.stringify(moved).includes(secret),false);
assert.throws(()=>transferClaim({...args,expectedHash:"sha256:stale"}),/stale or replayed/);
assert.throws(()=>transferClaim({...args,targetCapability:"wrong-capability-that-is-still-long-enough"}),/trusted registry/);
assert.throws(()=>transferClaim({...args,seatRegistry:{[b]:{...registry[b],capability_fingerprint:seatFingerprint("different-trusted-capability-333333333333")}}}),/trusted registry/);
assert.throws(()=>transferClaim({...args,targetSeat:a}),/self-transfer/); assert.throws(()=>transferClaim({...args,issuerRole:"maker"}),/IT Manager III/);
assert.throws(()=>transferClaim({...args,lease:sealLease({...lease,revoked:true})}),/stale, revoked/);
assert.throws(()=>transferClaim({...args,activeClaims:[{ticket:"OTHER",ref:"other",path_globs:["src/feature/widget/**"]}]}),/collision/);
assert.throws(()=>recoverExpiredClaim(args),/not expired/); assert.equal(recoverExpiredClaim({...args,now:"2026-08-30T11:01:00Z",expiry:"2026-08-30T12:00:00Z"}).event.kind,"expired-claim-recovered");
const root=fs.mkdtempSync(path.join(os.tmpdir(),"seat-claims-")), cf=path.join(root,"claim.json"), lf=path.join(root,"lease.json"), ed=path.join(root,"events"), lock=path.join(root,"claim.lock"); atomicWriteJson(cf,claim); atomicWriteJson(lf,lease);
const committed=commitClaimTransfer({claimFile:cf,leaseFile:lf,eventDir:ed,lockFile:lock,expectedEventTail:null,...args}); assert.deepEqual(JSON.parse(fs.readFileSync(cf,"utf8")),committed.claim); assert.deepEqual(JSON.parse(fs.readFileSync(lf,"utf8")),committed.lease); assert.equal(fs.readdirSync(ed).length,1);
const crash=fs.mkdtempSync(path.join(os.tmpdir(),"seat-crash-")), ccf=path.join(crash,"claim.json"), clf=path.join(crash,"lease.json"), ced=path.join(crash,"events"), clk=path.join(crash,"lock"); atomicWriteJson(ccf,claim); atomicWriteJson(clf,lease);
assert.throws(()=>commitClaimTransfer({claimFile:ccf,leaseFile:clf,eventDir:ced,lockFile:clk,expectedEventTail:null,...args,failAfterEvent:true}),/simulated crash/); assert.equal(fs.existsSync(`${clk}.journal.json`),true);
assert.throws(()=>commitClaimTransfer({claimFile:ccf,leaseFile:clf,eventDir:ced,lockFile:clk,expectedEventTail:null,...args}),/event tail CAS/); assert.equal(JSON.parse(fs.readFileSync(ccf,"utf8")).seat_id,b); assert.equal(fs.existsSync(`${clk}.journal.json`),false);
console.log("PASS 25/25; trusted-registry-proof=yes; lease-currentness=yes; secrets-recorded0; CAS-replay-refused=yes; collision-refused=yes; expiry-recovery=yes; event-tail-CAS=yes; journal-recovery=yes; claim+lease+event-transaction=yes; Project-writes=0; protected-writes=0");
