import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { assignLiveClaim } from "./pipeline-seat-assignment.mjs";
import { atomicWriteJson, sealClaim, sealLease, seatFingerprint } from "./pipeline-seat-claims.mjs";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "seat-live-assignment-"));
const runtime = path.join(root, "runtime");
const targetSeat = "seat:application:22222222-2222-4222-8222-222222222222";
const holdingSeat = "seat:application:11111111-1111-4111-8111-111111111111";
const capability = "target-seat-secret-2222222222222222222222222222";
const claim = sealClaim({ schema: "agentops/seat-claim/v1", revision: 1, parent_hash: null, ticket: "AS-HD-040", seat_id: holdingSeat, lease_id: "lease-AS-HD-040", ref: "codex/art-040", path_globs: ["assets/classes/**"], issued: "2026-08-30T10:00:00Z", expiry: "2026-08-30T11:00:00Z", status: "active" });
const lease = sealLease({ schema: "agentops/seat-lease/v1", revision: 1, parent_hash: null, id: claim.lease_id, actor: "maker", seat_id: holdingSeat, issuer: "it-manager-iii", ticket: claim.ticket, ref: claim.ref, path_globs: claim.path_globs, issued: claim.issued, expiry: claim.expiry, revoked: false });
atomicWriteJson(path.join(runtime, "claims", `${claim.ticket}.json`), claim);
atomicWriteJson(path.join(runtime, "leases", `${lease.id}.json`), lease);
atomicWriteJson(path.join(runtime, "registry.json"), { schema: "agentops/seat-registry/v1", seats: { [targetSeat]: { role: "maker", status: "active", path_globs: ["assets/classes/**"], capability_fingerprint: seatFingerprint(capability) } } });
fs.mkdirSync(path.join(runtime, "secrets"), { recursive: true });
fs.writeFileSync(path.join(runtime, "secrets", "maker.cap"), capability);
const configFile = path.join(runtime, "seat-runtime.json");
atomicWriteJson(configFile, { schema: "agentops/seat-runtime/v1", issuer_role: "it-manager-iii", lease_seconds: 3600, registry_file: "registry.json", claims_dir: "claims", leases_dir: "leases", events_dir: "events", lock_file: "claim-transaction.lock", seats: { maker: { seat_id: targetSeat, capability_file: "secrets/maker.cap" } } });
const offer = { status: "OFFERED", released_actor: "maker", selected: { ticket: claim.ticket, lease: claim.lease_id, ref: claim.ref, path_globs: claim.path_globs } };
const assigned = assignLiveClaim(root, { offer, now: "2026-08-30T10:30:00Z", runtimeConfigFile: configFile });
assert.equal(assigned.status, "ASSIGNED");
assert.equal(assigned.seat_id, targetSeat);
assert.match(assigned.audit_event, /^sha256:/);
assert.equal(JSON.stringify(assigned).includes(capability), false);
assert.equal(fs.readdirSync(path.join(runtime, "events", claim.ticket)).length, 1);
const replay = assignLiveClaim(root, { offer, now: "2026-08-30T10:31:00Z", runtimeConfigFile: configFile });
assert.equal(replay.status, "ALREADY_ASSIGNED");
assert.equal(fs.readdirSync(path.join(runtime, "events", claim.ticket)).length, 1);
assert.throws(() => assignLiveClaim(root, { offer: { ...offer, selected: { ...offer.selected, ref: "wrong" } }, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile }), /does not bind/);
assert.throws(() => assignLiveClaim(root, { offer: { ...offer, released_actor: "help-desk" }, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile }), /no unique seat/);
atomicWriteJson(path.join(runtime, "seat-runtime-escape.json"), { ...JSON.parse(fs.readFileSync(configFile, "utf8")), registry_file: "../registry.json" });
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:32:00Z", runtimeConfigFile: path.join(runtime, "seat-runtime-escape.json") }), /must stay inside/);
const registry = JSON.parse(fs.readFileSync(path.join(runtime, "registry.json"), "utf8"));
atomicWriteJson(path.join(runtime, "registry.json"), { ...registry, seats: { [targetSeat]: { ...registry.seats[targetSeat], path_globs: ["docs/**"] } } });
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile }), /path eligibility/);
atomicWriteJson(path.join(runtime, "registry.json"), registry);
fs.writeFileSync(path.join(runtime, "secrets", "maker.cap"), "wrong-capability-that-is-still-long-enough");
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile }), /proof failed/);
console.log("PASS 14/14; immediate-assignment=yes; canonical-claim-CAS=yes; unique-seat=yes; trusted-proof=yes; path-eligibility=yes; replay-transfer0; audit-event1; secret-output0; offer-binding=yes; missing-seat-refused=yes; runtime-path-escape-refused=yes; bad-proof-refused=yes; Project-writes=0; protected-writes=0");
