import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { acquireClaimLock, atomicWriteJson, commitClaimTransfer, recoverExpiredClaim, sealClaim, sealLease, seatFingerprint, transferClaim, validateLease } from "./pipeline-seat-claims.mjs";
const a="seat:feature-architecture:11111111-1111-4111-8111-111111111111", b="seat:feature-architecture:22222222-2222-4222-8222-222222222222", secret="target-seat-secret-capability-2222222222222222";
const registry={ [b]:{role:"maker",status:"active",capability_fingerprint:seatFingerprint(secret)} };
const claim=sealClaim({schema:"agentops/seat-claim/v1",revision:1,parent_hash:null,ticket:"AS-HD-269",seat_id:a,lease_id:"lease-269",ref:"codex/issue-269",path_globs:["src/feature/**"],issued:"2026-08-30T10:00:00Z",expiry:"2026-08-30T11:00:00Z",status:"active"});
const lease=sealLease({schema:"agentops/seat-lease/v1",revision:1,parent_hash:null,id:"lease-269",actor:"maker",seat_id:a,issuer:"it-manager-iii",ticket:"AS-HD-269",ref:"codex/issue-269",path_globs:["src/feature/**"],issued:"2026-08-30T10:00:00Z",expiry:"2026-08-30T11:00:00Z",revoked:false});
assert.equal(validateLease(lease,claim,"2026-08-30T10:30:00Z"),lease);
const args={claim,lease,expectedHash:claim.current_hash,targetSeat:b,targetCapability:secret,seatRegistry:registry,issuerRole:"it-manager-iii",now:"2026-08-30T10:30:00Z",expiry:"2026-08-30T11:30:00Z",activeClaims:[]};
const moved=transferClaim(args); assert.equal(moved.claim.seat_id,b); assert.equal(moved.lease.seat_id,b); assert.equal(moved.claim.parent_hash,claim.current_hash); assert.match(moved.event.event_hash,/^sha256:/); assert.equal(JSON.stringify(moved).includes(secret),false);
assert.throws(()=>transferClaim({...args,expectedHash:"sha256:stale"}),/stale or replayed/);
assert.throws(()=>transferClaim({...args,targetCapability:"wrong-capability-that-is-still-long-enough"}),/trusted registry/);
assert.throws(()=>transferClaim({...args,seatRegistry:{[b]:{...registry[b],capability_fingerprint:seatFingerprint("different-trusted-capability-333333333333")}}}),/trusted registry/);
assert.throws(()=>transferClaim({...args,targetSeat:a}),/self-transfer/); assert.throws(()=>transferClaim({...args,issuerRole:"maker"}),/IT Manager III/);
assert.throws(()=>transferClaim({...args,lease:sealLease({...lease,revoked:true})}),/stale, revoked/);
const overlappingClaim=sealClaim({...claim,ticket:"OTHER",lease_id:"lease-other",seat_id:"seat:feature-architecture:33333333-3333-4333-8333-333333333333",ref:"other",path_globs:["src/feature/widget/**"],current_hash:undefined});
assert.throws(()=>transferClaim({...args,activeClaims:[overlappingClaim]}),/collision/);
assert.throws(()=>recoverExpiredClaim(args),/not expired/); assert.equal(recoverExpiredClaim({...args,now:"2026-08-30T11:01:00Z",expiry:"2026-08-30T12:00:00Z"}).event.kind,"expired-claim-recovered");
const root=fs.mkdtempSync(path.join(os.tmpdir(),"seat-claims-")), cf=path.join(root,"claims","claim.json"), lf=path.join(root,"leases","lease.json"), ed=path.join(root,"events"), lock=path.join(root,"claim.lock"); atomicWriteJson(cf,claim); atomicWriteJson(lf,lease);
const committed=commitClaimTransfer({claimFile:cf,leaseFile:lf,eventDir:ed,lockFile:lock,expectedEventTail:null,...args}); assert.deepEqual(JSON.parse(fs.readFileSync(cf,"utf8")),committed.claim); assert.deepEqual(JSON.parse(fs.readFileSync(lf,"utf8")),committed.lease); assert.equal(fs.readdirSync(ed).length,1);
const crash=fs.mkdtempSync(path.join(os.tmpdir(),"seat-crash-")), ccf=path.join(crash,"claims","claim.json"), clf=path.join(crash,"leases","lease.json"), ced=path.join(crash,"events"), clk=path.join(crash,"lock"); atomicWriteJson(ccf,claim); atomicWriteJson(clf,lease);
assert.throws(()=>commitClaimTransfer({claimFile:ccf,leaseFile:clf,eventDir:ced,lockFile:clk,expectedEventTail:null,...args,failAfterEvent:true}),/simulated crash/); assert.equal(fs.existsSync(`${clk}.journal.json`),true);
assert.throws(()=>commitClaimTransfer({claimFile:ccf,leaseFile:clf,eventDir:ced,lockFile:clk,expectedEventTail:null,...args}),/event tail CAS/); assert.equal(JSON.parse(fs.readFileSync(ccf,"utf8")).seat_id,b); assert.equal(fs.existsSync(`${clk}.journal.json`),false);
const pre=fs.mkdtempSync(path.join(os.tmpdir(),"seat-pre-event-")), pcf=path.join(pre,"claims","claim.json"), plf=path.join(pre,"leases","lease.json"), ped=path.join(pre,"events"), plk=path.join(pre,"lock"); atomicWriteJson(pcf,claim); atomicWriteJson(plf,lease);
assert.throws(()=>commitClaimTransfer({claimFile:pcf,leaseFile:plf,eventDir:ped,lockFile:plk,expectedEventTail:null,...args,failAfterJournal:true}),/after journal/);
assert.throws(()=>commitClaimTransfer({claimFile:pcf,leaseFile:plf,eventDir:ped,lockFile:plk,expectedEventTail:null,...args}),/event tail CAS/); assert.equal(fs.readdirSync(ped).length,1); assert.equal(JSON.parse(fs.readFileSync(pcf,"utf8")).seat_id,b);
const neg=fs.mkdtempSync(path.join(os.tmpdir(),"seat-denominator-")), ncf=path.join(neg,"claims","claim.json"), nlf=path.join(neg,"leases","lease.json"), ned=path.join(neg,"events"), nlk=path.join(neg,"lock"); atomicWriteJson(ncf,claim); atomicWriteJson(nlf,lease);
const other=sealClaim({...claim,ticket:"OTHER",lease_id:"lease-other",seat_id:"seat:feature-architecture:33333333-3333-4333-8333-333333333333",ref:"other",current_hash:undefined}); atomicWriteJson(path.join(neg,"claims","other.json"),other);
assert.throws(()=>commitClaimTransfer({claimFile:ncf,leaseFile:nlf,eventDir:ned,lockFile:nlk,expectedEventTail:null,...args}),/collision/);
atomicWriteJson(path.join(neg,"claims","other.json"),{...other,current_hash:"sha256:forged"}); assert.throws(()=>commitClaimTransfer({claimFile:ncf,leaseFile:nlf,eventDir:ned,lockFile:nlk,expectedEventTail:null,...args}),/seal mismatch/);
atomicWriteJson(path.join(neg,"claims","other.json"),sealClaim({...claim,seat_id:"seat:feature-architecture:44444444-4444-4444-8444-444444444444",current_hash:undefined})); assert.throws(()=>commitClaimTransfer({claimFile:ncf,leaseFile:nlf,eventDir:ned,lockFile:nlk,expectedEventTail:null,...args}),/duplicate active claim/);
const liveLock=path.join(fs.mkdtempSync(path.join(os.tmpdir(),"seat-live-lock-")),"claim.lock"), held=acquireClaimLock(liveLock); assert.throws(()=>acquireClaimLock(liveLock),/live pid/); held.release();
const crashFixture=new URL("./pipeline-seat-claims-crash-fixture.mjs",import.meta.url);
function hardCrash(kind) {
  const hard=fs.mkdtempSync(path.join(os.tmpdir(),`seat-hard-${kind}-`)), hcf=path.join(hard,"claims","claim.json"), hlf=path.join(hard,"leases","lease.json"), hed=path.join(hard,"events"), hlk=path.join(hard,"lock"), cfg=path.join(hard,"config.json");
  atomicWriteJson(hcf,claim); atomicWriteJson(hlf,lease);
  atomicWriteJson(cfg,{claimFile:hcf,leaseFile:hlf,eventDir:hed,lockFile:hlk,expectedEventTail:null,expectedHash:claim.current_hash,targetSeat:b,targetCapability:secret,seatRegistry:registry,issuerRole:"it-manager-iii",now:"2026-08-30T10:30:00Z",expiry:"2026-08-30T11:30:00Z",[kind]:true});
  const child=spawnSync(process.execPath,[crashFixture.pathname.replace(/^\/(.:)/,"$1"),cfg],{windowsHide:true});
  assert.equal(child.status,kind==="hardExitAfterJournal"?86:87); assert.equal(fs.existsSync(hlk),true); assert.equal(fs.existsSync(`${hlk}.journal.json`),true);
  assert.throws(()=>commitClaimTransfer({claimFile:hcf,leaseFile:hlf,eventDir:hed,lockFile:hlk,expectedEventTail:null,...args}),/event tail CAS/);
  assert.equal(JSON.parse(fs.readFileSync(hcf,"utf8")).seat_id,b); assert.equal(fs.readdirSync(hed).length,1); assert.equal(fs.existsSync(hlk),false); assert.equal(fs.existsSync(`${hlk}.journal.json`),false);
}
hardCrash("hardExitAfterJournal"); hardCrash("hardExitAfterEvent");
const corrupt=fs.mkdtempSync(path.join(os.tmpdir(),"seat-corrupt-lock-")), corruptLock=path.join(corrupt,"lock"); fs.writeFileSync(corruptLock,"not-json\n"); assert.throws(()=>acquireClaimLock(corruptLock),/fail-closed/); assert.equal(fs.existsSync(corruptLock),true);
const corruptJournal=fs.mkdtempSync(path.join(os.tmpdir(),"seat-corrupt-journal-")), jcf=path.join(corruptJournal,"claims","claim.json"), jlf=path.join(corruptJournal,"leases","lease.json"), jed=path.join(corruptJournal,"events"), jlk=path.join(corruptJournal,"lock"), jcfg=path.join(corruptJournal,"config.json"); atomicWriteJson(jcf,claim); atomicWriteJson(jlf,lease); atomicWriteJson(jcfg,{claimFile:jcf,leaseFile:jlf,eventDir:jed,lockFile:jlk,expectedEventTail:null,expectedHash:claim.current_hash,targetSeat:b,targetCapability:secret,seatRegistry:registry,issuerRole:"it-manager-iii",now:"2026-08-30T10:30:00Z",expiry:"2026-08-30T11:30:00Z",hardExitAfterJournal:true}); const dead=spawnSync(process.execPath,[crashFixture.pathname.replace(/^\/(.:)/,"$1"),jcfg],{windowsHide:true}); assert.equal(dead.status,86); fs.writeFileSync(`${jlk}.journal.json`,"{\"schema\":\"foreign\"}\n"); assert.throws(()=>commitClaimTransfer({claimFile:jcf,leaseFile:jlf,eventDir:jed,lockFile:jlk,expectedEventTail:null,...args}),/journal is corrupt or foreign/); assert.equal(fs.existsSync(`${jlk}.journal.json`),true);
console.log("PASS 43/43; authoritative-denominator=yes; omitted-collision-caught=yes; unsealed-claim-refused=yes; duplicate-ticket-refused=yes; trusted-registry-proof=yes; lease-currentness=yes; secrets-recorded0; CAS-replay-refused=yes; expiry-recovery=yes; event-tail-CAS=yes; soft-crash-recovery=yes; hard-exit-after-journal-recovery=yes; hard-exit-after-event-recovery=yes; duplicate-event0; live-lock-not-stolen=yes; corrupt-lock-fail-closed=yes; corrupt-journal-preserved=yes; claim+lease+event-transaction=yes; Project-writes=0; protected-writes=0");
