import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { assignLiveClaim, resolveCanonicalSeatRuntime } from "./pipeline-seat-assignment.mjs";
import { atomicWriteJson, sealClaim, sealLease, seatFingerprint } from "./pipeline-seat-claims.mjs";
import { cycle, readState } from "./pipeline-pilot-watch.mjs";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "seat-live-assignment-"));
const actualAgentops = path.resolve(new URL("../", import.meta.url).pathname.replace(/^\/(.:)/, "$1"));
assert.match(resolveCanonicalSeatRuntime(actualAgentops).replaceAll("\\", "/"), /AshenSpire\/.git\/agentops-pipeline\/runtime$/);
const runtime = path.join(root, "runtime");
const targetSeat = "seat:application:22222222-2222-4222-8222-222222222222";
const holdingSeat = "seat:application:11111111-1111-4111-8111-111111111111";
const capability = "target-seat-secret-2222222222222222222222222222";
const claim = sealClaim({ schema: "agentops/seat-claim/v1", revision: 1, parent_hash: null, ticket: "AS-HD-040", seat_id: holdingSeat, lease_id: "lease-AS-HD-040", ref: "codex/art-040", path_globs: ["assets/classes/**"], issued: "2026-08-30T10:00:00Z", expiry: "2026-08-30T11:00:00Z", status: "active" });
const lease = sealLease({ schema: "agentops/seat-lease/v1", revision: 1, parent_hash: null, id: claim.lease_id, actor: "maker", seat_id: holdingSeat, issuer: "it-manager-iii", ticket: claim.ticket, ref: claim.ref, path_globs: claim.path_globs, issued: claim.issued, expiry: claim.expiry, revoked: false });
atomicWriteJson(path.join(runtime, "claims", `${claim.ticket}.json`), claim);
atomicWriteJson(path.join(runtime, "leases", `${lease.id}.json`), lease);
atomicWriteJson(path.join(runtime, "registry.json"), { schema: "agentops/seat-registry/v1", seats: { [targetSeat]: { role: "maker", status: "active", path_globs: ["assets/classes/**"], capability_fingerprint: seatFingerprint(capability) } } });
fs.mkdirSync(path.join(runtime, "secrets"), { recursive: true });
fs.writeFileSync(path.join(runtime, "secrets", "maker.cap"), capability);
const configFile = path.join(runtime, "seat-runtime.json");
atomicWriteJson(configFile, { schema: "agentops/seat-runtime/v1", issuer_role: "it-manager-iii", lease_seconds: 3600, registry_file: "registry.json", claims_dir: "claims", leases_dir: "leases", events_dir: "events", lock_file: "claim-transaction.lock", seats: { maker: { seat_id: targetSeat, capability_file: "secrets/maker.cap" } } });
const offer = { status: "OFFERED", released_actor: "maker", selected: { ticket: claim.ticket, lease: claim.lease_id, ref: claim.ref, path_globs: claim.path_globs } };
const assigned = assignLiveClaim(root, { offer, now: "2026-08-30T10:30:00Z", runtimeConfigFile: configFile, canonicalRuntimeRoot: runtime });
assert.equal(assigned.status, "ASSIGNED");
assert.equal(assigned.seat_id, targetSeat);
assert.match(assigned.audit_event, /^sha256:/);
assert.equal(JSON.stringify(assigned).includes(capability), false);
assert.equal(fs.readdirSync(path.join(runtime, "events", claim.ticket)).length, 1);
const replay = assignLiveClaim(root, { offer, now: "2026-08-30T10:31:00Z", runtimeConfigFile: configFile, canonicalRuntimeRoot: runtime });
assert.equal(replay.status, "ALREADY_ASSIGNED");
assert.equal(fs.readdirSync(path.join(runtime, "events", claim.ticket)).length, 1);
assert.throws(() => assignLiveClaim(root, { offer: { ...offer, selected: { ...offer.selected, ref: "wrong" } }, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile, canonicalRuntimeRoot: runtime }), /does not bind/);
assert.throws(() => assignLiveClaim(root, { offer: { ...offer, released_actor: "help-desk" }, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile, canonicalRuntimeRoot: runtime }), /no unique seat/);
atomicWriteJson(path.join(runtime, "seat-runtime-escape.json"), { ...JSON.parse(fs.readFileSync(configFile, "utf8")), registry_file: "../registry.json" });
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:32:00Z", runtimeConfigFile: path.join(runtime, "seat-runtime-escape.json"), canonicalRuntimeRoot: runtime }), /must stay inside/);
atomicWriteJson(path.join(runtime, "seat-runtime-unc.json"), { ...JSON.parse(fs.readFileSync(configFile, "utf8")), registry_file: "\\\\server\\share\\registry.json" });
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:32:00Z", runtimeConfigFile: path.join(runtime, "seat-runtime-unc.json"), canonicalRuntimeRoot: runtime }), /must stay inside/);
const registry = JSON.parse(fs.readFileSync(path.join(runtime, "registry.json"), "utf8"));
atomicWriteJson(path.join(runtime, "registry.json"), { ...registry, seats: { [targetSeat]: { ...registry.seats[targetSeat], path_globs: ["docs/**"] } } });
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile, canonicalRuntimeRoot: runtime }), /path eligibility/);
atomicWriteJson(path.join(runtime, "registry.json"), registry);
fs.writeFileSync(path.join(runtime, "secrets", "maker.cap"), "wrong-capability-that-is-still-long-enough");
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:32:00Z", runtimeConfigFile: configFile, canonicalRuntimeRoot: runtime }), /proof failed/);
const forged = path.join(root, "forged-runtime");
fs.cpSync(runtime, forged, { recursive: true });
const agentops = path.join(root, ".agentops");
fs.mkdirSync(path.join(agentops, "work", "DONE"), { recursive: true });
fs.writeFileSync(path.join(agentops, "work", "DONE", "CURRENT.json"), JSON.stringify({ ticket: "DONE", lifecycle_state: "resolved", owner_actor: "maker", current_hash: "sha256:done" }));
const watcherState = path.join(root, "watcher-state.json");
const forgedOffer = { ...offer, completed_ticket: "DONE" };
const refused = cycle({ root: agentops, stateFile: watcherState, now: "2026-08-30T10:33:00Z", offer: () => forgedOffer, assign: (_root, options) => assignLiveClaim(agentops, { ...options, canonicalRuntimeRoot: runtime }), runtimeConfigFile: path.join(forged, "seat-runtime.json") });
assert.equal(refused.events[0].result.assignment.status, "FAILED");
assert.equal(readState(watcherState).processed.length, 0);
assert.equal(readState(watcherState).pending.length, 1);
const outside = path.join(root, "outside-runtime");
fs.mkdirSync(outside);
atomicWriteJson(path.join(outside, "registry.json"), registry);
fs.symlinkSync(outside, path.join(runtime, "junction"), "junction");
atomicWriteJson(path.join(runtime, "seat-runtime-junction.json"), { ...JSON.parse(fs.readFileSync(configFile, "utf8")), registry_file: "junction/registry.json" });
assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:34:00Z", runtimeConfigFile: path.join(runtime, "seat-runtime-junction.json"), canonicalRuntimeRoot: runtime }), /symlink or junction|resolves outside/);
let directSymlinkChecked = false;
try {
  fs.symlinkSync(path.join(outside, "registry.json"), path.join(runtime, "registry-link.json"), "file");
  atomicWriteJson(path.join(runtime, "seat-runtime-file-link.json"), { ...JSON.parse(fs.readFileSync(configFile, "utf8")), registry_file: "registry-link.json" });
  assert.throws(() => assignLiveClaim(root, { offer, now: "2026-08-30T10:34:00Z", runtimeConfigFile: path.join(runtime, "seat-runtime-file-link.json"), canonicalRuntimeRoot: runtime }), /symlink or junction|resolves outside/);
  directSymlinkChecked = true;
} catch (error) {
  if (!["EPERM", "EACCES"].includes(error.code)) throw error;
}
console.log(`PASS 21/21; linked-worktree-common-runtime=yes; immediate-assignment=yes; canonical-claim-CAS=yes; unique-seat=yes; trusted-proof=yes; path-eligibility=yes; replay-transfer0; audit-event1; secret-output0; offer-binding=yes; missing-seat-refused=yes; runtime-path-escape-refused=yes; UNC-runtime-refused=yes; sibling-runtime-refused=yes; refused-terminal-unprocessed=yes; junction-escape-refused=yes; direct-file-link=${directSymlinkChecked ? "refused" : "unsupported"}; bad-proof-refused=yes; Project-writes=0; protected-writes=0`);
