// Presentation component identifiers. This is the UI equivalent of a small
// enum: Component Models and Views share the names without either owning the
// other's implementation.
export const UI_COMPONENTS = Object.freeze({
  sharedRunHud: 'shared-run-hud',
  runHeaderStrip: 'run-header-strip',
  identityCluster: 'identity-cluster',
  portraitBadge: 'portrait-badge',
  characterTitle: 'character-title',
  cindersCounter: 'cinders-counter',
  buildMetadataTrail: 'build-metadata-trail',
  metadataField: 'metadata-field',
  primaryHudRow: 'primary-hud-row',
  panel: 'panel',
  componentBackground: 'component-background',
  vitalsPanel: 'vitals-panel',
  resourceMeter: 'resource-meter',
  quickAccessPanel: 'quick-access-panel',
  actionControl: 'action-control',
  hotkeyBadge: 'hotkey-badge',
  armouryControl: 'armoury-control',
  quickMenuControl: 'quick-menu-control',
  quickMenuPanel: 'quick-menu-panel',
  quickMenuCaption: 'quick-menu-caption',
  quickMenuRow: 'quick-menu-row',
  menuOverlay: 'menu-overlay',
  menuTabStrip: 'menu-tab-strip',
  menuTab: 'menu-tab',
  menuPanel: 'menu-panel',
  crimsonFlaskControl: 'crimson-flask-control',
  azureFlaskControl: 'azure-flask-control',
  inventoryBelt: 'inventory-belt',
  itemTray: 'item-tray',
  itemSlot: 'item-slot',
  relicTray: 'relic-tray',
  relicSlot: 'relic-slot',
  potionTray: 'potion-tray',
  potionControl: 'potion-control',
  armouryOverlay: 'armoury-overlay',
  armouryPanel: 'armoury-panel',
  armouryHeader: 'armoury-header',
  armouryViewSwitcher: 'armoury-view-switcher',
  armouryBody: 'armoury-body',
  armouryFigure: 'armoury-figure',
  equipmentSlot: 'equipment-slot',
  equipmentSetCell: 'equipment-set-cell',
  armouryInventory: 'armoury-inventory',
  inventoryItemCard: 'inventory-item-card',
  inventoryDetailCard: 'inventory-detail-card',
  equipmentComparison: 'equipment-comparison',
  armouryStatsPanel: 'armoury-stats-panel',
  armouryCardStrip: 'armoury-card-strip',
  armouryRegionHeader: 'armoury-region-header',
  foldingTray: 'folding-tray',
  trayHeader: 'tray-header',
  trayResizeHandle: 'tray-resize-handle',
  trayContent: 'tray-content',
  battlefieldStage: 'battlefield-stage',
  combatantFrame: 'combatant-frame',
  playerCombatantFrame: 'player-combatant-frame',
  enemyCombatantFrame: 'enemy-combatant-frame',
  combatantSprite: 'combatant-sprite',
  combatantNameplate: 'combatant-nameplate',
  intentIndicator: 'intent-indicator',
  blockBadge: 'block-badge',
  healthStatusBar: 'health-status-bar',
  poiseStatusBar: 'poise-status-bar',
  procStatusBar: 'proc-status-bar',
  arcaneExposureBar: 'arcane-exposure-bar',
  statusEffectTray: 'status-effect-tray',
  tooltip: 'tooltip',
  damageFeedback: 'damage-feedback',
  guardedDamageIndicator: 'guarded-damage-indicator',
  healthDamageIndicator: 'health-damage-indicator',
  playerHandTray: 'player-hand-tray',
  combatActionRail: 'combat-action-rail',
});

const KNOWN_COMPONENTS = new Set(Object.values(UI_COMPONENTS));

export function isUiComponentId(component) {
  return KNOWN_COMPONENTS.has(component);
}
