import assert from 'node:assert/strict';
import { snapshotEnemyKnowledgeRules } from '../src/model/enemyKnowledgeRules.js';
import { openRunEnemyKnowledge, openKnowledgeEncounter, addKnowledgeCounterBonus, reconcilePerception, acknowledgeKnowledgeBank, enemyKnowledgeRunProblems } from '../src/model/enemyKnowledgeRun.js';
import { emptyEnemyKnowledge, bankEnemyKnowledgeProfile, knowledgePoints } from '../src/model/enemyKnowledgeProfile.js';
const newRun = receiptId => {
  const run = { seed: 42, skills: {}, enemyKnowledgeRules: snapshotEnemyKnowledgeRules() };
  openRunEnemyKnowledge(run, { receiptId, bankable: true }); return run;
};
const run = newRun('unique-run-a'), second = newRun('unique-run-b');
const encounter = openKnowledgeEncounter(run, 'node', 'fight', ['soldier', 'soldier']);
assert.deepEqual(encounter.enemyIds, ['soldier']);
assert.equal(knowledgePoints(run.enemyKnowledgeState.pending.enemies.soldier), 1);
run.enemyKnowledgeState.pending = addKnowledgeCounterBonus(run.enemyKnowledgeState.pending, encounter, 'soldier', 30);
run.enemyKnowledgeState.pending = addKnowledgeCounterBonus(run.enemyKnowledgeState.pending, encounter, 'soldier', 30);
assert.equal(knowledgePoints(run.enemyKnowledgeState.pending.enemies.soldier), 2);
const other = openKnowledgeEncounter(second, 'node', 'fight', ['soldier']);
assert.notEqual(encounter.id, other.id);
let banked = bankEnemyKnowledgeProfile({}, run.enemyKnowledgeState.pending).meta;
banked = bankEnemyKnowledgeProfile(banked, second.enemyKnowledgeState.pending).meta;
assert.equal(knowledgePoints(banked.enemyKnowledge.enemies.soldier), 3);
assert.equal(bankEnemyKnowledgeProfile(banked, run.enemyKnowledgeState.pending).changed, false);
const captured = structuredClone(second.enemyKnowledgeState.pending);
second.enemyKnowledgeState.pending = addKnowledgeCounterBonus(second.enemyKnowledgeState.pending, other, 'soldier', 30);
acknowledgeKnowledgeBank(second, captured);
assert.equal(second.enemyKnowledgeState.pending.enemies.soldier.receipts[other.id].bonus, true);
acknowledgeKnowledgeBank(second, structuredClone(second.enemyKnowledgeState.pending));
assert.deepEqual(second.enemyKnowledgeState.pending, emptyEnemyKnowledge());
const nextVisit = openKnowledgeEncounter(run, 'node', 'fight', ['soldier'], banked.enemyKnowledge);
assert.notEqual(nextVisit.id, encounter.id);
assert.equal(nextVisit.visit, 2);
assert.equal(reconcilePerception(run, encounter.id, 3).levelUps, 1);
const afterCredit = structuredClone(run);
assert.equal(reconcilePerception(run, encounter.id, 3).gained, 0);
assert.deepEqual(run.skills, afterCredit.skills);
assert.equal(reconcilePerception(run, encounter.id, 4).gained, 1);
assert.deepEqual(enemyKnowledgeRunProblems(run, new Set(['soldier'])), []);
const restored = JSON.parse(JSON.stringify(run));
assert.deepEqual(enemyKnowledgeRunProblems(restored, new Set(['soldier'])), []);
assert.deepEqual(openKnowledgeEncounter(restored, 'node', 'fight', ['soldier']), openKnowledgeEncounter(run, 'node', 'fight', ['soldier']));
assert.deepEqual(reconcilePerception(restored, encounter.id, 5), reconcilePerception(run, encounter.id, 5));
assert.deepEqual(restored, run);
const pendingFailure = newRun('failed-write-run');
for (let n = 0; n < 100; n++) openKnowledgeEncounter(pendingFailure, `n${n}`, 'fight', ['soldier']);
assert.equal(Object.keys(pendingFailure.enemyKnowledgeState.pending.enemies.soldier.receipts).length, 30);
assert.deepEqual(enemyKnowledgeRunProblems(pendingFailure), []);
assert.throws(() => openRunEnemyKnowledge(newRun('x'), { bankable: true, receiptId: null }), /unique run receipt/);
assert.equal(openRunEnemyKnowledge({ skills: {} }, { bankable: true, receiptId: 'legacy' }), false);
assert.deepEqual(enemyKnowledgeRunProblems({ skills: {} }), []);
const collisionA = newRun('a'), collisionB = newRun('a/1/x');
assert.notEqual(openKnowledgeEncounter(collisionA, 'x/1/y', 'z', ['soldier']).id, openKnowledgeEncounter(collisionB, 'y', 'z', ['soldier']).id);
const longRun = newRun('long-run');
const longBefore = JSON.stringify(longRun);
assert.throws(() => openKnowledgeEncounter(longRun, 'x'.repeat(250), 'fight', ['soldier']), /too long/);
assert.equal(JSON.stringify(longRun), longBefore);
const malformedIdentity = structuredClone(run);
malformedIdentity.enemyKnowledgeState.currentEncounter.id = 'unrelated-receipt';
assert.ok(enemyKnowledgeRunProblems(malformedIdentity).length);
restored.enemyKnowledgeState.appliedXp.bad = -1;
assert.ok(enemyKnowledgeRunProblems(restored).length);
console.log('PASS enemy knowledge runs: duplicate enemies, unique repeated-seed runs, retry/acknowledgment, bounded failed banks and exact XP continuation');
