import assert from 'node:assert/strict';
import { bankRunEnemyKnowledge } from '../src/engine/enemyKnowledgeSave.js';
import { createProfileStorageOwner } from '../src/engine/profileStorageOwner.js';
import { emptyEnemyKnowledge, knowledgePoints } from '../src/model/enemyKnowledgeProfile.js';
const receipt = (id, bonus = false) => ({ version: 1, enemies: { soldier: { target: 30, receipts: { [id]: { bonus } } } } });
const makeRun = (id, bonus = false) => ({ enemyKnowledgeState: { bankable: true, pending: receipt(id, bonus) } });
let meta = { enemyKnowledge: emptyEnemyKnowledge(), settings: { music: true } };
let fail = false, discard = false, quarantined = false;
const saves = { loadMeta: () => structuredClone(meta), profileStatus: () => ({ quarantined }),
  saveMeta(value) { if (fail) return { ok: false, reason: 'quota exceeded' }; if (!discard) meta = structuredClone(value); return { ok: true }; } };
const owner = createProfileStorageOwner({ key: 'knowledge-save-test' });
const a = makeRun('a'), b = makeRun('b');
const results = await Promise.all([bankRunEnemyKnowledge(saves, owner, a), bankRunEnemyKnowledge(saves, owner, b)]);
assert.ok(results.every(r => r.ok)); assert.equal(knowledgePoints(meta.enemyKnowledge.enemies.soldier), 2);
assert.deepEqual(a.enemyKnowledgeState.pending, emptyEnemyKnowledge()); assert.deepEqual(b.enemyKnowledgeState.pending, emptyEnemyKnowledge());
assert.deepEqual(meta.settings, { music: true });
const retry = makeRun('c'); fail = true;
assert.equal((await bankRunEnemyKnowledge(saves, owner, retry)).reason, 'quota exceeded'); assert.ok(retry.enemyKnowledgeState.pending.enemies.soldier);
fail = false; assert.equal((await bankRunEnemyKnowledge(saves, owner, retry)).ok, true);
const replay = makeRun('c'); assert.equal((await bankRunEnemyKnowledge(saves, owner, replay)).changed, false);
assert.equal(knowledgePoints(meta.enemyKnowledge.enemies.soldier), 3);
const unverified = makeRun('d'); discard = true;
assert.match((await bankRunEnemyKnowledge(saves, owner, unverified)).reason, /read-back/); assert.ok(unverified.enemyKnowledgeState.pending.enemies.soldier);
discard = false; quarantined = true;
assert.match((await bankRunEnemyKnowledge(saves, owner, unverified)).reason, /quarantined/); quarantined = false;
const malformed = makeRun('bad'); malformed.enemyKnowledgeState.pending.enemies.soldier.target = 1;
assert.equal((await bankRunEnemyKnowledge(saves, owner, malformed)).ok, false);
// A successful base-point bank cannot acknowledge a tactical bonus that was
// earned after capture while the bank waited for browser ownership.
let release; const gate = new Promise(r => { release = r; });
const blockedOwner = { mutate: async operation => { await gate; return operation(); } };
const live = makeRun('late'); const pending = bankRunEnemyKnowledge(saves, blockedOwner, live);
live.enemyKnowledgeState.pending.enemies.soldier.receipts.late.bonus = true;
release(); assert.equal((await pending).ok, true);
assert.equal(live.enemyKnowledgeState.pending.enemies.soldier.receipts.late.bonus, true);
assert.equal((await bankRunEnemyKnowledge(saves, owner, live)).ok, true);
assert.deepEqual(live.enemyKnowledgeState.pending, emptyEnemyKnowledge());
assert.equal(meta.enemyKnowledge.enemies.soldier.receipts.late.bonus, true);
const damagedRun = makeRun('newer');
const lossy = { ...saves, saveMeta(value) {
  meta = structuredClone(value); delete meta.enemyKnowledge.enemies.soldier.receipts.a;
  return { ok: true };
} };
assert.match((await bankRunEnemyKnowledge(lossy, owner, damagedRun)).reason, /complete ledger/);
assert.ok(damagedRun.enemyKnowledgeState.pending.enemies.soldier.receipts.a);
assert.equal((await bankRunEnemyKnowledge(saves, owner, damagedRun)).ok, true);
assert.ok(meta.enemyKnowledge.enemies.soldier.receipts.a);
const lostBonus = makeRun('after-bonus');
const downgrading = { ...saves, saveMeta(value) { meta = structuredClone(value); meta.enemyKnowledge.enemies.soldier.receipts.late.bonus = false; return { ok: true }; } };
assert.equal((await bankRunEnemyKnowledge(downgrading, owner, lostBonus)).ok, false);
assert.equal(lostBonus.enemyKnowledgeState.pending.enemies.soldier.receipts.late.bonus, true);
assert.equal((await bankRunEnemyKnowledge(saves, owner, lostBonus)).ok, true);
assert.equal(meta.enemyKnowledge.enemies.soldier.receipts.late.bonus, true);
const interrupted = makeRun('interrupted');
const throwing = { ...saves, saveMeta(value) { meta = structuredClone(value); delete meta.enemyKnowledge.enemies.soldier.receipts.b; throw new Error('storage interrupted'); } };
assert.equal((await bankRunEnemyKnowledge(throwing, owner, interrupted)).reason, 'storage interrupted');
assert.ok(interrupted.enemyKnowledgeState.pending.enemies.soldier.receipts.b);
assert.equal((await bankRunEnemyKnowledge(saves, owner, interrupted)).ok, true);
assert.ok(meta.enemyKnowledge.enemies.soldier.receipts.b);
const targetRecovery = makeRun('target-corruption');
const changingTarget = { ...saves, saveMeta(value) { meta = structuredClone(value); meta.enemyKnowledge.enemies.soldier.target = 20; return { ok: true }; } };
assert.equal((await bankRunEnemyKnowledge(changingTarget, owner, targetRecovery)).ok, false);
assert.equal(targetRecovery.enemyKnowledgeState.recoveryTargets.soldier, 30);
const savedRecovery = JSON.parse(JSON.stringify(targetRecovery));
assert.equal((await bankRunEnemyKnowledge(saves, owner, savedRecovery)).ok, true);
assert.equal(meta.enemyKnowledge.enemies.soldier.target, 30);
assert.deepEqual(savedRecovery.enemyKnowledgeState.recoveryTargets, {});
// A normal stale incoming target is distinct from a detected storage failure.
meta.enemyKnowledge.enemies.soldier.target = 20;
const ordinaryStale = makeRun('ordinary-stale');
assert.equal((await bankRunEnemyKnowledge(saves, owner, ordinaryStale)).ok, true);
assert.equal(meta.enemyKnowledge.enemies.soldier.target, 20);
console.log('PASS enemy knowledge banking helper: serialized receipt unions, verified durability, failure retry, replay deduplication and captured acknowledgments');
