// tests/web-meta.test.mjs — the web edition carries its share/install metadata.
//
// FINISH §13 "Web and store metadata" (owner decision D8: web only; D5 web
// edition): a meta description, og:title / og:description / og:image, an icon
// link and theme-color. index.html is the source; tools/bundle.mjs copies the
// tags into the single-file build through tools/head-meta.mjs.
//
//   node --test tests/web-meta.test.mjs

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { REQUIRED_HEAD_META, headMetaTags } from '../tools/head-meta.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(resolve(ROOT, p), 'utf8');

const valueOf = (tag) => (/\b(?:content|href)=(["'])(.*?)\1/i.exec(tag) || [])[2] || '';
const tagFor = (html, name) => REQUIRED_HEAD_META.find(([n]) => n === name)[1].exec(html)?.[0];

test('index.html carries every required web meta tag, each with a value', () => {
  const html = read('index.html');
  const head = html.slice(0, html.indexOf('</head>'));
  for (const [name] of REQUIRED_HEAD_META) {
    const tag = tagFor(head, name);
    assert.ok(tag, `index.html <head> has no ${name}`);
    assert.ok(valueOf(tag).trim().length > 0, `${name} is empty`);
  }
  const image = valueOf(tagFor(head, 'og:image'));
  assert.match(image, /^https:\/\//, 'og:image must be an absolute https URL (crawlers do not resolve relative ones)');
  const local = /\/main\/(assets\/[^?#]+)$/.exec(image);
  if (local) assert.ok(existsSync(resolve(ROOT, local[1])), `og:image points at ${local[1]}, which is not in the tree`);
  assert.match(valueOf(tagFor(head, 'theme-color')), /^#[0-9a-f]{6}$/i, 'theme-color is a hex colour');
  assert.match(valueOf(tagFor(head, 'icon link')), /^data:image\//, 'the icon is inline so the single-file build needs no extra file');
});

test('the bundler copies the tags from index.html into the build head', () => {
  const tags = headMetaTags(read('index.html'));
  for (const [name, re] of REQUIRED_HEAD_META) {
    assert.ok(tags.some((t) => re.test(t)), `headMetaTags() drops the ${name}`);
  }
  const bundle = read('tools/bundle.mjs');
  assert.match(bundle, /headMetaTags\(indexHtml\)/, 'tools/bundle.mjs no longer reads the tags from index.html');
  assert.match(bundle, /<title>\$\{title\}<\/title>\n\$\{headMeta\./, 'tools/bundle.mjs no longer writes the tags into its <head>');
  assert.throws(() => headMetaTags('<head><title>x</title></head>'), /missing meta description, og:title/);
});

// The built files are regenerated by the merge train, not by feature branches,
// so a build that predates this change has none of the tags. Once a build
// carries any of them it must carry all of them.
for (const built of ['build/AshenSpire.html', 'build/AshenSpire-mobile.html']) {
  test(`${built} carries every web meta tag once it is rebuilt`, (t) => {
    const path = resolve(ROOT, built);
    if (!existsSync(path)) return t.skip(`${built} not present`);
    const start = readFileSync(path).subarray(0, 1 << 16).toString('utf8');
    if (start.startsWith('version https://git-lfs')) return t.skip(`${built} is an LFS pointer`);
    const head = start.slice(0, start.indexOf('</title>') + 4096);
    if (!REQUIRED_HEAD_META.some(([, re]) => re.test(head))) {
      return t.skip(`${built} predates the web meta tags; the merge train rebuilds it`);
    }
    for (const [name, re] of REQUIRED_HEAD_META) assert.ok(re.test(head), `${built} has no ${name}`);
  });
}
