import {SEQUENCES,DURATIONS} from '../combined-reference/transitions/sequences.mjs';
import {SCHEMA,uuid,clone,placement,entry,validateProject,moveEntry,gapMatches} from './model.mjs';
import * as storage from './storage.mjs';
import {preparePose,splitFile} from './images.mjs';
const $=id=>document.getElementById(id),catalog=await fetch('art/pose-editor/catalog.json').then(r=>{if(!r.ok)throw Error('Pose catalog could not load.');return r.json()}),poses=new Map(catalog.poses.map(p=>[p.id,p])),cache=new Map();
let sequence,requests=[],selected=0,playing=false,loadingPlayback=false,playbackToken=0,timer,saveTimer,drawVersion=0,undo=[],redo=[],drag=null,dragScroll,stageDrag=null,requestGap=0,busy=false;
const qp=new URLSearchParams(location.search),starter=SEQUENCES[qp.get('class')]?qp.get('class'):'reaver';
function message(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);for(const dialog of document.querySelectorAll('dialog[open]')){let status=dialog.querySelector('.dialog-status');if(!status){status=textEl('p','','dialog-status');status.setAttribute('role','status');dialog.append(status)}status.textContent=text;status.classList.toggle('error',error)}}
function button(text,fn,attrs={}){const b=document.createElement('button');b.type='button';b.textContent=text;Object.assign(b,attrs);b.onclick=fn;return b}
function textEl(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
function image(pose){const img=new Image();img.src=pose.src;img.alt=pose.label;img.draggable=false;if(pose.kind==='uploaded')prepared(pose).then(a=>{img.src=a.silhouette.toDataURL('image/png')}).catch(e=>message(e.message,true));return img}
function project(){return {schema:SCHEMA,sequence:clone(sequence),poses:[...poses.values()].filter(p=>p.kind==='uploaded').map(p=>clone(p)),requests:clone(requests)}}
function snapshot(){return {sequence:clone(sequence),requests:clone(requests)}}
function syncPlaybackControls(){
 const label=loadingPlayback?'Loading frames…':playing?'Ⅱ Pause sequence':'▶ Play sequence';
 for(const id of ['play','timeline-play']){$(id).textContent=label;$(id).disabled=!current()||loadingPlayback;$(id).setAttribute('aria-pressed',String(playing))}
 $('playback-state').textContent=current()?`${playing?'Playing':loadingPlayback?'Loading':'Ready'} · Frame ${selected+1} of ${sequence.entries.length}`:'Add poses to play a sequence';
}
function stop(){playbackToken++;playing=false;loadingPlayback=false;clearTimeout(timer);syncPlaybackControls()}
function autosave(){clearTimeout(saveTimer);$('save-state').textContent='Unsaved changes';saveTimer=setTimeout(async()=>{try{await storage.write('draft',project());$('save-state').textContent='Draft saved in this workspace'}catch(e){message(`Local save failed: ${e.message}. Export JSON to preserve your work.`,true)}},200)}
function changed(){sequence.revision++;autosave();render()}
function edit(fn){stop();undo.push(snapshot());if(undo.length>50)undo.shift();redo=[];fn();selected=Math.max(0,Math.min(selected,sequence.entries.length-1));changed()}
function restoreHistory(from,to){if(!from.length)return;stop();const isUndo=from===undo,revision=sequence.revision;to.push(snapshot());const old=from.pop();sequence=old.sequence;requests=old.requests;sequence.revision=revision;selected=Math.min(selected,Math.max(0,sequence.entries.length-1));changed();message(isUndo?'Undid the last edit.':'Redid the last edit.')}
function seed(key){const s=SEQUENCES[key];return {id:uuid(),name:s.title,revision:0,entries:(s.order||[0,1,2,3,4,5,6]).map(i=>({...entry(`reference:${key}:pose-${String(i+1).padStart(2,'0')}`),durationMs:DURATIONS[i]}))}}
const current=()=>sequence.entries[selected];
function add(poseId,index=sequence.entries.length){if(sequence.entries.length>=500){message('A sequence can contain up to 500 entries.',true);return}edit(()=>{sequence.entries.splice(index,0,entry(poseId));selected=index})}
function remove(index){if(index<0||index>=sequence.entries.length)return;edit(()=>sequence.entries.splice(index,1));message('Occurrence removed. The pose remains in the library. Undo restores it.')}
function select(index){stop();selected=index;render()}
function prepared(p){if(!cache.has(p.id))cache.set(p.id,preparePose(p).catch(e=>{cache.delete(p.id);throw e}));return cache.get(p.id)}
async function paint(ctx,e,alpha=1){const p=poses.get(e.poseId),asset=await prepared(p),t=e.placement,s=p.scale*t.scale;ctx.save();ctx.globalAlpha=alpha;ctx.translate(330+t.x,490+t.y);ctx.scale(s,s);ctx.drawImage($('display').value==='silhouette'?asset.silhouette:asset.image,-p.pivot.x-t.pivotX,-p.pivot.y-t.pivotY);ctx.restore()}
async function draw(){const token=++drawVersion,c=document.createElement('canvas');c.width=600;c.height=560;const ctx=c.getContext('2d');ctx.fillStyle='#303233';ctx.fillRect(0,0,600,560);ctx.strokeStyle='#8b785766';ctx.beginPath();ctx.moveTo(15,490);ctx.lineTo(585,490);ctx.stroke();
 try{if(current()){if($('onion').checked&&sequence.entries.length>1){const prev=(selected+sequence.entries.length-1)%sequence.entries.length;await paint(ctx,sequence.entries[prev],0.22)}await paint(ctx,current())}else{ctx.fillStyle='#c6bba5';ctx.font='18px system-ui';ctx.fillText('Add a pose from the library to begin.',125,260)}ctx.strokeStyle='#e6bc70';ctx.beginPath();ctx.moveTo(323,490);ctx.lineTo(337,490);ctx.moveTo(330,483);ctx.lineTo(330,497);ctx.stroke();if(token===drawVersion)$('viewer').getContext('2d').drawImage(c,0,0)}catch(e){message(`Could not display pose: ${e.message}`,true)}
}
function renderSelection(){const e=current(),p=e&&poses.get(e.poseId);$('frame-info').textContent=e?`${selected+1} / ${sequence.entries.length} · ${p.label} · ${p.id}`:'Empty action list';
 for(const el of $('timeline').querySelectorAll('[data-index]'))el.classList.toggle('selected',Number(el.dataset.index)===selected);
 for(const id of ['duration','pos-x','pos-y','scale','pivot-x','pivot-y','duplicate','remove','align','earlier','later'])$(id).disabled=!e;
 if(e){for(const[id,val]of Object.entries({duration:e.durationMs,'pos-x':e.placement.x,'pos-y':e.placement.y,scale:e.placement.scale,'pivot-x':e.placement.pivotX,'pivot-y':e.placement.pivotY}))$(id).value=val}
 syncPlaybackControls();$('back').disabled=!e;$('next').disabled=!e;draw();
 window.poseEditor={sequence:clone(sequence),selected,playing,poseCount:poses.size,requests:clone(requests)};
}
function renderTimeline(){const nodes=[];sequence.entries.forEach((e,i)=>{if(i>0){const gap=button('+',()=>openRequest(i-1));gap.className='gap';gap.dataset.gap=i;gap.setAttribute('aria-label',`Request transition between ${i} and ${i+1}`);nodes.push(gap)}const p=poses.get(e.poseId),tile=document.createElement('div');tile.className='tile';tile.dataset.index=i;const img=image(p);img.onpointerdown=event=>startDrag(event,{kind:'entry',index:i,poseId:p.id});const title=textEl('span',`${i+1}. ${p.label}`,'pose-name');title.title=p.id;tile.append(img,title,textEl('small',`${e.durationMs} ms`));const actions=document.createElement('div');actions.className='bar actions';actions.append(button('Select',()=>select(i)),button('×',()=>remove(i),{ariaLabel:`Remove occurrence ${i+1}`}));tile.append(actions);nodes.push(tile)});
 const end=button('+ Drop a pose here',()=>{$('search').focus();$('library').scrollIntoView({behavior:'smooth',block:'center'})});end.className='extender';end.dataset.gap=sequence.entries.length;end.id='append-zone';nodes.push(end);$('timeline').replaceChildren(...nodes);$('entry-count').textContent=`(${sequence.entries.length} occurrences)`;
}
function render(){ $('name').value=sequence.name;$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;renderTimeline();renderSelection();renderRequests() }
function renderLibrary(){const search=$('search').value.toLowerCase(),cls=$('class-filter').value,kind=$('kind-filter').value,found=[...poses.values()].filter(p=>(!cls||p.classId===cls)&&(!kind||p.kind===kind)&&`${p.id} ${p.label}`.toLowerCase().includes(search));$('pose-count').textContent=`(${found.length} / ${poses.size})`;
 $('library').replaceChildren(...found.map(p=>{const tile=document.createElement('article');tile.className='tile';tile.dataset.poseId=p.id;const img=image(p);img.loading='lazy';img.onpointerdown=e=>startDrag(e,{kind:'pose',poseId:p.id});const name=textEl('span',p.label,'pose-name');name.title=p.label;tile.append(img,name,textEl('code',p.id));const controls=document.createElement('div');controls.className='bar';controls.append(button('Add',()=>add(p.id)),button('Replace',()=>{if(!current()){message('Select an occurrence to replace, or use Add.',true);return}edit(()=>{current().poseId=p.id});message('Pose replaced; occurrence timing and placement retained.')}));tile.append(controls);return tile}));
}
function advance(delta){if(!sequence.entries.length)return;selected=(selected+delta+sequence.entries.length)%sequence.entries.length;renderSelection()}
function schedule(){clearTimeout(timer);if(!playing||!current())return;timer=setTimeout(()=>{if(selected===sequence.entries.length-1&&!$('loop').checked){stop();renderSelection();return}advance(1);schedule()},current().durationMs/Number($('speed').value))}
async function startPlayback(){if(!current()||loadingPlayback)return;const token=++playbackToken;loadingPlayback=true;syncPlaybackControls();try{await Promise.all([...new Set(sequence.entries.map(e=>e.poseId))].map(id=>prepared(poses.get(id))));if(token!==playbackToken)return;loadingPlayback=false;playing=true;renderSelection();schedule()}catch(e){if(token!==playbackToken)return;stop();renderSelection();message(e.message,true)}}
function toggleSequencePlayback(){if(playing){stop();renderSelection();return}selected=0;renderSelection();$('viewer').closest('.workspace').scrollIntoView({block:'start',behavior:'instant'});startPlayback()}

function distanceOutside(x,y,r){return Math.hypot(Math.max(r.left-x,0,x-r.right),Math.max(r.top-y,0,y-r.bottom))}
function startDrag(e,data){if(e.button!==0)return;drag={...data,startX:e.clientX,startY:e.clientY,pointerId:e.pointerId,active:false};e.currentTarget.setPointerCapture(e.pointerId)}
function clearDrag(){cancelAnimationFrame(dragScroll);document.getElementById('drag-ghost')?.remove();document.getElementById('drag-message')?.remove();$('timeline').classList.remove('drop-active');drag=null}
function scrollDrag(){if(!drag?.active)return;const r=$('timeline').getBoundingClientRect();if(distanceOutside(drag.x,drag.y,r)>0){if(drag.y<55)window.scrollBy(0,-12);else if(drag.y>innerHeight-55)window.scrollBy(0,12)}dragScroll=requestAnimationFrame(scrollDrag)}
document.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;if(!drag.active&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<7)return;
 drag.x=e.clientX;drag.y=e.clientY;if(!drag.active){drag.active=true;stop();const ghost=document.createElement('div');ghost.id='drag-ghost';ghost.append(image(poses.get(drag.poseId)));document.body.append(ghost);const hint=textEl('div','Drop into the timeline');hint.id='drag-message';document.body.append(hint);scrollDrag()}
 const ghost=$('drag-ghost');ghost.style.left=`${e.clientX+12}px`;ghost.style.top=`${e.clientY+12}px`;const r=$('timeline').getBoundingClientRect(),outside=distanceOutside(e.clientX,e.clientY,r),removeNow=drag.kind==='entry'&&outside>56;$('drag-message').textContent=removeNow?'Release to remove · Undo available':outside===0?'Release to insert here':'Return to timeline to place';$('drag-message').classList.toggle('remove',removeNow);$('timeline').classList.toggle('drop-active',outside===0);
 if(outside===0){if(e.clientX>r.right-35)$('timeline').scrollLeft+=16;else if(e.clientX<r.left+35)$('timeline').scrollLeft-=16}
});
document.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointerId)return;const d=drag,r=$('timeline').getBoundingClientRect(),outside=distanceOutside(e.clientX,e.clientY,r);clearDrag();if(!d.active){if(d.kind==='entry')select(d.index);return}if(d.kind==='entry'&&outside>56){remove(d.index);return}if(outside>0){message('Drag cancelled.');return}
 const target=document.elementFromPoint(e.clientX,e.clientY),gap=target?.closest('[data-gap]'),tile=target?.closest('[data-index]');let at=sequence.entries.length;
 if(gap)at=Number(gap.dataset.gap);else if(tile){const b=tile.getBoundingClientRect();at=Number(tile.dataset.index)+(e.clientX>b.left+b.width/2?1:0)}
 if(d.kind==='pose')add(d.poseId,at);else edit(()=>{const eid=sequence.entries[d.index].entryId;sequence.entries=moveEntry(sequence.entries,d.index,at);selected=sequence.entries.findIndex(v=>v.entryId===eid)})
});
document.addEventListener('pointercancel',clearDrag);document.addEventListener('keydown',e=>{if(e.key==='Escape'){clearDrag();$('request-dialog').close()}if((e.ctrlKey||e.metaKey)&&e.key==='z'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();restoreHistory(e.shiftKey?redo:undo,e.shiftKey?undo:redo)}});
// Activate touch buttons on release, including immediately after a captured drag.
// Suppress the compatibility click if the browser sends one as well.
let touchButton=null,lastTouchButton=null;
document.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;const b=e.target.closest('button');touchButton=b&&!b.disabled?{b,id:e.pointerId,x:e.clientX,y:e.clientY}:null});
document.addEventListener('pointerup',e=>{const t=touchButton;touchButton=null;if(!t||t.id!==e.pointerId||Math.hypot(e.clientX-t.x,e.clientY-t.y)>10)return;const r=t.b.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;e.preventDefault();lastTouchButton={b:t.b,time:performance.now()};t.b.click()});
document.addEventListener('pointercancel',()=>{touchButton=null});
document.addEventListener('click',e=>{if(e.isTrusted&&e.detail>0&&lastTouchButton&&e.target.closest('button')===lastTouchButton.b&&performance.now()-lastTouchButton.time<700){e.preventDefault();e.stopImmediatePropagation()}},true);
const viewer=$('viewer');viewer.onpointerdown=e=>{if(e.button!==0||!current())return;stop();stageDrag={x:e.clientX,y:e.clientY,before:snapshot(),placement:clone(current().placement),index:selected,pointerId:e.pointerId};viewer.setPointerCapture(e.pointerId)};
viewer.onpointermove=e=>{if(!stageDrag||e.pointerId!==stageDrag.pointerId)return;const rect=viewer.getBoundingClientRect(),p=current().placement;p.x=Math.round(stageDrag.placement.x+(e.clientX-stageDrag.x)*600/rect.width);p.y=Math.round(stageDrag.placement.y+(e.clientY-stageDrag.y)*560/rect.height);renderSelection()};
viewer.onpointerup=e=>{if(!stageDrag||e.pointerId!==stageDrag.pointerId)return;undo.push(stageDrag.before);redo=[];stageDrag=null;changed()};viewer.onpointercancel=()=>{if(stageDrag){sequence=stageDrag.before.sequence;stageDrag=null;render()}};
async function download(name,data){const safeName=name.replace(/[^a-zA-Z0-9_.-]/g,'-'),json=JSON.stringify(data,null,2);if(window.poseStudio)return window.poseStudio.exportJSON(safeName,json);const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=safeName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true}
async function savedList(){const keys=await storage.list(),options=[Object.assign(document.createElement('option'),{value:'',textContent:'Choose a saved sequence'})];for(const key of keys){const p=await storage.read(key);options.push(Object.assign(document.createElement('option'),{value:key,textContent:p.sequence.name}))}$('saved').replaceChildren(...options)}
function restore(data){const valid=validateProject(data,poses);for(const p of valid.uploads){const existing=poses.get(p.id);if(existing&&existing.src!==p.src)throw Error('Uploaded pose ID conflicts with a different image. Import into a fresh workspace.');}
 for(const p of valid.uploads)poses.set(p.id,p);sequence=valid.sequence;requests=Array.isArray(data.requests)?data.requests.filter(r=>r&&typeof r.id==='string'&&typeof r.notes==='string'&&r.left&&r.right&&poses.has(r.left.poseId)&&poses.has(r.right.poseId)&&Array.isArray(r.candidates)).map(r=>({...r,candidates:r.candidates.filter(id=>poses.has(id))})):[];selected=0;stop();undo=[];redo=[];renderLibrary();render();autosave();
}
async function upload(files,{append=false,candidateRequest=null,grid=null}={}){if(busy)return;busy=true;message('Reading sprites…');try{const added=[],pending=[];for(const file of Array.from(files)){const frames=await splitFile(file,{rows:grid?.rows??Number($('rows').value),cols:grid?.cols??Number($('cols').value),remove:$('key-bg').checked,tolerance:Math.max(0,Math.min(100,Number($('tolerance').value)||0))});for(const f of frames){const p={...f,id:`upload:${uuid()}`,classId:$('class-filter').value||'uploaded',outfit:'uploaded',kind:'uploaded'};pending.push(p);added.push(p.id)}}if(!added.length){message('No non-empty frames found.',true);return}if([...poses.values()].filter(p=>p.kind==='uploaded').length+pending.length>1000)throw Error('This workspace supports up to 1,000 uploaded poses.');if(append&&sequence.entries.length+added.length>500)throw Error('This drop exceeds the 500-entry timeline limit. Import into the library instead.');for(const p of pending)poses.set(p.id,p);
 if(candidateRequest){edit(()=>{candidateRequest.candidates.push(...added);candidateRequest.status='candidates'})}else if(append){edit(()=>{sequence.entries.push(...added.map(id=>entry(id)));selected=sequence.entries.length-added.length})}else autosave();
 $('display').value='silhouette';$('kind-filter').value='uploaded';$('class-filter').value='';$('search').value='';renderLibrary();renderRequests();draw();message(`Imported ${added.length} poses with black silhouettes. Add or drag them into the action list.`)}catch(e){message(e.message,true)}finally{busy=false;$('uploads').value='';renderLibrary()}}
function openRequest(gap){if(!sequence.entries[gap+1])return;requestGap=gap;$('request-description').textContent=`${poses.get(sequence.entries[gap].poseId).label} → ${poses.get(sequence.entries[gap+1].poseId).label}`;$('request-dialog').showModal()}
function createRequest(){const left=sequence.entries[requestGap],right=sequence.entries[requestGap+1];if(!left||!right)return;edit(()=>requests.push({id:`transition:${uuid()}`,sequenceId:sequence.id,revision:sequence.revision,left:clone(left),right:clone(right),context:clone(sequence.entries.slice(Math.max(0,requestGap-1),requestGap+3)),count:Number($('request-count').value),notes:$('request-notes').value.slice(0,3000),status:'requested',candidates:[]}));$('request-dialog').close();message('Request saved. Export it for generation, then load candidates for review.')}
async function exportRequest(r){try{const refs=[];for(const e of r.context){const p=poses.get(e.poseId),a=await prepared(p),c=document.createElement('canvas');c.width=600;c.height=560;const ctx=c.getContext('2d');await paint(ctx,e);refs.push({entry:e,poseId:p.id,image:c.toDataURL('image/png')})}const exported=await download(`${r.id}.json`,{schema:'ashenspire.transition-request/v1',request:clone(r),references:refs,prompt:`Generate ${r.count} intermediate black silhouette poses that naturally connect the exact endpoint images. Preserve character scale, feet contact, weapon shape and length, hand grip and direction of motion. Use neighboring frames for momentum. Keep the weapon part of the drawing. ${r.notes}`});message(exported?'Transition request exported with aligned reference images.':'Export canceled.')}catch(e){message(e.message,true)}}
function renderRequests(){if(!requests.length){$('requests').replaceChildren(textEl('p','No requests yet.','muted'));return}$('requests').replaceChildren(...requests.map(r=>{const box=document.createElement('article');box.className='request';box.dataset.requestId=r.id;const matches=gapMatches(sequence,r);box.append(textEl('h3',`${r.count} transition frames · ${r.status}`),textEl('small',`${r.id} · captured revision ${r.revision}`));const ends=document.createElement('div');ends.className='endpoints';ends.append(image(poses.get(r.left.poseId)),textEl('span','→'),image(poses.get(r.right.poseId)));box.append(ends,textEl('p',r.notes||'Connect the endpoints naturally.'),textEl('small',matches?'Endpoint gap is still intact.':'Endpoint gap changed. Restore the original adjacent entries to accept these candidates.'));
 const actions=document.createElement('div');actions.className='bar';const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='image/png,image/webp,image/jpeg';input.className='file-input';input.setAttribute('aria-label','Load transition candidates');const gridInputs={};for(const key of ['rows','cols']){const label=textEl('label',key==='rows'?'Rows':'Columns'),field=document.createElement('input');field.type='number';field.min=1;field.max=64;field.value=1;field.dataset[`candidate${key==='rows'?'Rows':'Cols'}`]='';label.append(field);gridInputs[key]=field;actions.append(label)}input.onchange=()=>upload(input.files,{candidateRequest:r,grid:{rows:Number(gridInputs.rows.value),cols:Number(gridInputs.cols.value)}});actions.append(button('Export request',()=>exportRequest(r)),input);box.append(actions);
 const candidates=document.createElement('div');candidates.className='candidates';for(const id of r.candidates){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=true;check.value=id;label.append(image(poses.get(id)),check,textEl('small',poses.get(id).label));candidates.append(label)}box.append(candidates);
 const accept=button('Accept selected into gap',()=>{const ids=[...candidates.querySelectorAll('input:checked')].map(c=>c.value);if(!ids.length||!gapMatches(sequence,r)){message('Choose candidates and restore the matching endpoint gap first.',true);return}if(sequence.entries.length+ids.length>500){message('Sequence limit is 500 entries.',true);return}edit(()=>{const index=sequence.entries.findIndex(e=>e.entryId===r.left.entryId)+1;sequence.entries.splice(index,0,...ids.map(id=>entry(id)));selected=index;r.status='accepted'});message('Candidates inserted in file order. Reorder them in the timeline as needed.')});accept.disabled=!matches||!r.candidates.length;box.append(accept);return box}))}
for(const[key,s]of Object.entries(SEQUENCES))$('preset').append(Object.assign(document.createElement('option'),{value:key,textContent:s.title}));$('preset').value=starter;
for(const cls of ['reaver','rogue','starseer','herald','uploaded'])$('class-filter').append(Object.assign(document.createElement('option'),{value:cls,textContent:cls}));
for(const id of ['search','class-filter','kind-filter'])$(id).addEventListener(id==='search'?'input':'change',renderLibrary);
$('play').onclick=$('timeline-play').onclick=toggleSequencePlayback;$('back').onclick=()=>{stop();advance(-1)};$('next').onclick=()=>{stop();advance(1)};$('speed').onchange=schedule;$('onion').onchange=$('display').onchange=draw;
$('name').onchange=()=>edit(()=>sequence.name=$('name').value.trim().slice(0,120)||'Untitled sequence');
for(const[id,key]of [['duration','durationMs'],['pos-x','x'],['pos-y','y'],['scale','scale'],['pivot-x','pivotX'],['pivot-y','pivotY']])$(id).onchange=()=>{if(!current())return;const v=Number($(id).value),min=Number($(id).min),max=Number($(id).max);if(!Number.isFinite(v)||v<min||v>max){message(`Use a value from ${min} to ${max}.`,true);renderSelection();return}edit(()=>{if(key==='durationMs')current()[key]=v;else current().placement[key]=v})};
$('align').onclick=()=>edit(()=>current().placement=placement());$('duplicate').onclick=()=>{if(!current()||sequence.entries.length>=500)return;edit(()=>{sequence.entries.splice(selected+1,0,{...clone(current()),entryId:uuid()});selected++})};$('remove').onclick=()=>remove(selected);
$('earlier').onclick=()=>{if(selected>0)edit(()=>{sequence.entries=moveEntry(sequence.entries,selected,selected-1);selected--})};$('later').onclick=()=>{if(selected<sequence.entries.length-1)edit(()=>{sequence.entries=moveEntry(sequence.entries,selected,selected+2);selected++})};
$('undo').onclick=()=>restoreHistory(undo,redo);$('redo').onclick=()=>restoreHistory(redo,undo);
$('reset').onclick=()=>edit(()=>{sequence=seed($('preset').value);requests=[];selected=0});$('new').onclick=()=>edit(()=>{sequence={id:uuid(),name:'New action',revision:0,entries:[]};requests=[];selected=0});
$('save').onclick=async()=>{try{await storage.write(`saved:${sequence.id}`,project());await savedList();$('saved').value=`saved:${sequence.id}`;message(`Saved “${sequence.name}” in this workspace. Export JSON for a portable copy.`)}catch(e){message(`Save failed: ${e.message}`,true)}};
$('load').onclick=async()=>{if(!$('saved').value)return;try{restore(await storage.read($('saved').value));message('Saved sequence restored.')}catch(e){message(e.message,true)}};
$('export').onclick=async()=>{try{const exported=await download(`${sequence.name}.json`,project());message(exported?'Portable sequence exported, including uploaded sprites.':'Export canceled.')}catch(e){message(`Export failed: ${e.message}`,true)}};$('import').onclick=()=>$('json-file').click();$('json-file').onchange=async()=>{try{const f=$('json-file').files[0];if(!f)return;if(f.size>100e6)throw Error('Sequence file exceeds 100 MB.');restore(JSON.parse(await f.text()));message('Sequence imported with its uploaded poses.')}catch(e){message(e.message,true)}finally{$('json-file').value=''}};
$('uploads').onchange=()=>upload($('uploads').files);for(const zone of [$('upload-zone'),$('timeline')]){zone.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();zone.classList.add('dragover')}});zone.addEventListener('dragleave',()=>zone.classList.remove('dragover'));zone.addEventListener('drop',e=>{if(!e.dataTransfer.files.length)return;e.preventDefault();zone.classList.remove('dragover');upload(e.dataTransfer.files,{append:zone.id==='timeline'})})}
$('create-request').onclick=createRequest;$('cancel-request').onclick=()=>$('request-dialog').close();document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();clearDrag()}});window.addEventListener('blur',clearDrag);
sequence=seed(starter);try{const draft=await storage.read('draft');if(draft)restore(draft);await savedList()}catch(e){message(`Local storage unavailable: ${e.message}. JSON export remains available.`,true)}renderLibrary();render();if(qp.get('play')==='1')startPlayback();

// Shell controls keep secondary workflows out of the editing surface.
for(const [trigger,target] of [['open-project','project-dialog'],['upload-open','upload-dialog'],['requests-open','requests-dialog'],['help-open','help-dialog']])$(trigger).onclick=()=>$(target).showModal();
for(const button of document.querySelectorAll('[data-close]'))button.onclick=()=>$(button.dataset.close).close();
for(const id of ['reset','load'])$(id).addEventListener('click',()=>{if(id==='reset'||$('saved').value)$('project-dialog').close()});
$('properties-toggle').onclick=()=>{const open=document.querySelector('.panel').classList.toggle('is-open');$('properties-toggle').setAttribute('aria-expanded',String(open));if(open)document.querySelector('.panel').scrollIntoView({block:'nearest'})};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){for(const dialog of document.querySelectorAll('dialog[open]'))dialog.close();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&!document.querySelector('dialog[open]')){e.preventDefault();document.activeElement?.blur();$(e.shiftKey?'export':'save').click();return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable||document.querySelector('dialog[open]'))return;if(e.code==='Space'&&!['BUTTON','SUMMARY'].includes(e.target.tagName)){e.preventDefault();if(!loadingPlayback)toggleSequencePlayback()}});
if(window.poseStudio){window.poseStudio.onAction(id=>{document.activeElement?.blur();$(id).click()});window.poseStudio.onPrepareClose(async()=>{clearTimeout(saveTimer);await storage.write('draft',project())});document.querySelector('.local-badge').textContent='● OFFLINE DESKTOP';}
