const canvas=(w,h)=>Object.assign(document.createElement('canvas'),{width:w,height:h});
export async function loadImage(src){const img=new Image();img.src=src;await img.decode();if(img.naturalWidth*img.naturalHeight>16e6)throw Error('Image exceeds 16 million pixels.');return img}
function bounds(c){const {data}=c.getContext('2d').getImageData(0,0,c.width,c.height);let left=c.width,top=c.height,right=-1,bottom=-1;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(data[(y*c.width+x)*4+3]>32){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y)}if(right<0)return null;const feet=[];for(let y=Math.max(top,bottom-4);y<=bottom;y++)for(let x=left;x<=right;x++)if(data[(y*c.width+x)*4+3]>32)feet.push(x);feet.sort((a,b)=>a-b);return {left,top,right,bottom,pivot:{x:feet[Math.floor(feet.length/2)]??(left+right)/2,y:bottom+1}}}
function removeBackground(c,tolerance){const ctx=c.getContext('2d'),im=ctx.getImageData(0,0,c.width,c.height),d=im.data,n=c.width*c.height,cornerIndices=[0,c.width-1,(c.height-1)*c.width,n-1];if(cornerIndices.some(p=>d[p*4+3]<200))return;const seen=new Uint8Array(n),q=new Int32Array(n);let h=0,t=0;const corners=cornerIndices.map(p=>Array.from(d.slice(p*4,p*4+3)));const bg=[0,1,2].map(k=>corners.map(p=>p[k]).sort((a,b)=>a-b)[1]);function add(p){if(seen[p])return;if(d[p*4+3]>0&&Math.max(...bg.map((v,k)=>Math.abs(d[p*4+k]-v)))>tolerance)return;seen[p]=1;q[t++]=p}for(let x=0;x<c.width;x++){add(x);add((c.height-1)*c.width+x)}for(let y=0;y<c.height;y++){add(y*c.width);add(y*c.width+c.width-1)}while(h<t){const p=q[h++],x=p%c.width,y=Math.floor(p/c.width);if(x)add(p-1);if(x+1<c.width)add(p+1);if(y)add(p-c.width);if(y+1<c.height)add(p+c.width)}for(let p=0;p<n;p++)if(seen[p])d[p*4+3]=0;ctx.putImageData(im,0,0)}
export async function splitFile(file,{rows=1,cols=1,remove=false,tolerance=25}={}){
 if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('Choose PNG, JPEG or WebP images up to 20 MB.');
 const url=URL.createObjectURL(file);let image;try{image=await loadImage(url)}finally{URL.revokeObjectURL(url)}
 if(!Number.isInteger(rows)||!Number.isInteger(cols)||rows<1||cols<1||rows*cols>64||rows>image.height||cols>image.width)throw Error('Use a grid of 1–64 cells with at least one pixel per cell.');
 const frames=[];
 for(let i=0;i<rows*cols;i++){const x=Math.floor(i%cols*image.width/cols),y=Math.floor(Math.floor(i/cols)*image.height/rows),w=Math.floor((i%cols+1)*image.width/cols)-x,h=Math.floor((Math.floor(i/cols)+1)*image.height/rows)-y,c=canvas(w,h);c.getContext('2d').drawImage(image,x,y,w,h,0,0,w,h);if(remove)removeBackground(c,tolerance);const b=bounds(c);if(b)frames.push({label:`${file.name.replace(/\.[^.]+$/,'')} · ${i+1}`,src:c.toDataURL('image/png'),width:w,height:h,pivot:b.pivot,visibleHeight:b.bottom-b.top+1})}
 const scale=Math.min(1,400/Math.max(1,...frames.map(f=>f.visibleHeight)),530/Math.max(1,...frames.map(f=>f.width)));
 return frames.map(({visibleHeight,...f})=>({...f,scale}));
}
export function silhouette(image){const c=canvas(image.naturalWidth||image.width,image.naturalHeight||image.height),ctx=c.getContext('2d'),mask=canvas(c.width,c.height),m=mask.getContext('2d');m.drawImage(image,0,0);m.globalCompositeOperation='source-in';m.fillStyle='#080909';m.fillRect(0,0,c.width,c.height);
 for(const [x,y]of [[-1,0],[1,0],[0,-1],[0,1]])ctx.drawImage(mask,x,y);ctx.globalCompositeOperation='source-in';ctx.fillStyle='#bfc7c5';ctx.fillRect(0,0,c.width,c.height);ctx.globalCompositeOperation='source-over';ctx.drawImage(mask,0,0);return c}
export async function preparePose(pose){const image=await loadImage(pose.src);if(!pose.pivot){const c=canvas(image.width,image.height);c.getContext('2d').drawImage(image,0,0);const b=bounds(c);pose.width=image.width;pose.height=image.height;pose.pivot=b?.pivot||{x:image.width/2,y:image.height};pose.scale=Math.min(1,400/Math.max(1,b?b.bottom-b.top+1:image.height),530/image.width)}return {image,silhouette:pose.kind==='reference'?image:silhouette(image)}}
