import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.POSE_STUDIO_PLAYWRIGHT?pathToFileURL(process.env.POSE_STUDIO_PLAYWRIGHT).href:'playwright');
const out=process.env.POSE_STUDIO_EVIDENCE;if(!out)throw Error('Set POSE_STUDIO_EVIDENCE to an output folder outside the repository');await mkdir(out,{recursive:true});
const origin=process.env.POSE_STUDIO_URL||'http://127.0.0.1:4318',browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});
const errors=[],checks=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/pose-studio/index.html');await page.locator('.effect').first().waitFor();assert.equal(await page.title(),'Pose & Effects · AshenSpire Studio');assert.equal(await page.locator('.effect').count(),80);await page.waitForTimeout(300);checks.push('identity, meaningful render and 80 effect tiles');
 await page.locator('#filter').selectOption('new');assert.equal(await page.locator('.effect').count(),24);
 await page.locator('[data-effect="edgeSweep"]').dragTo(page.locator('#stage'),{targetPosition:{x:260,y:240}});assert.equal(await page.locator('.clip').count(),2);assert.match(await page.locator('#selection').textContent(),/Edge glint/);checks.push('real library-to-stage drag');
 await page.locator('[data-field="size"]').fill('220');await page.locator('[data-field="size"]').press('Tab');assert.equal(await page.locator('[data-field="size"]').inputValue(),'220');await page.locator('#undo').click();assert.equal(await page.locator('[data-field="size"]').inputValue(),'160');await page.locator('#redo').click();assert.equal(await page.locator('[data-field="size"]').inputValue(),'220');checks.push('inspector edit and undo/redo');
 await page.locator('#pose-count').selectOption('7');assert.equal(await page.locator('.pose-cell').count(),7);await page.locator('#duration').fill('1600');await page.locator('#duration').press('Tab');
 await page.locator('#play').click();await page.waitForTimeout(150);assert.notEqual(await page.locator('#clock').textContent(),'0.00 s');await page.locator('#play').click();
 await page.locator('#flashes').check();await page.locator('#flashes').uncheck();await page.locator('#reduced').check();await page.locator('#reduced').uncheck();checks.push('seven poses, playback and accessibility toggles');
 const downloadEvent=page.waitForEvent('download');await page.locator('#save').click();const download=await downloadEvent,file=path.join(out,'roundtrip.pose.json');await download.saveAs(file);const saved=JSON.parse(await readFile(file,'utf8'));assert.ok(Object.keys(saved.assets).length>=12);assert.equal(saved.poses.length,7);
 await page.locator('#name').fill('Temporary change');await page.locator('#name').press('Tab');await page.locator('#project-file').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#name').value.includes('Shield bash'));assert.equal(await page.locator('.clip').count(),2);await page.reload();await page.locator('.clip').first().waitFor();assert.equal(await page.locator('.clip').count(),2);checks.push('portable package export/import and draft reload');
 await page.locator('#project-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":500}')});assert.match(await page.locator('#status').textContent(),/Unsupported project version/);assert.equal(await page.locator('.clip').count(),2);checks.push('invalid package rejection without lost edits');
 await page.locator('[data-tab="bindings"]').click();await page.locator('#test-tags').fill('shield');await page.locator('#test-mana').fill('0');await page.locator('#test-stamina').fill('0');assert.match(await page.locator('#resolution').textContent(),/Matched/);
 await page.locator('[data-binding-field="resource"]').selectOption('mana');assert.match(await page.locator('#resolution').textContent(),/No matching rule/);await page.locator('#test-mana').fill('2');assert.match(await page.locator('#resolution').textContent(),/Matched/);await page.screenshot({path:path.join(out,'bindings-desktop.png'),fullPage:true});checks.push('payment-conditioned binding explanation');
 await page.locator('[data-tab="relations"]').click();assert.ok(await page.locator('.node').count()>=3);await page.screenshot({path:path.join(out,'relationships-desktop.png'),fullPage:true});
 await page.locator('[data-tab="compose"]').click();await page.locator('[data-preset="blood"]').click();await page.locator('#filter').selectOption('new');await page.locator('[data-cue=contact]').click();await page.locator('#forward').click();await page.waitForTimeout(100);await page.screenshot({path:path.join(out,'studio-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'studio-phone.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('desktop and 390px layout without horizontal overflow');
 await page.setViewportSize({width:1440,height:1100});
 const popup=context.waitForEvent('page');await page.locator('#game').click();const game=await popup;game.on('pageerror',e=>errors.push(e.message));await game.waitForFunction(()=>window.__combat&&window.__renderCombatForShot);
 const result=await game.evaluate(async()=>{const c=window.__combat;c.player.energy=99;c.player.mana=99;c.player.stamina=99;c.piles.hand=[{instanceId:'studio-test',cardId:'gorefireSlash',upgraded:false}];window.__renderCombatForShot();const seen=new Set(),poll=setInterval(()=>document.querySelectorAll('.studio-combat-effect,.painted-combat-effect,.studio-pose-frame').forEach(el=>seen.add(el.dataset.effect||'authoredPose')),2);document.querySelector('[data-instance-id="studio-test"]').click();document.querySelector('.enemy:not(.dead)').click();await new Promise(r=>setTimeout(r,1300));clearInterval(poll);return {seen:[...seen],remaining:document.querySelectorAll('.studio-combat-effect,.studio-pose-frame').length};});assert.ok(result.seen.includes('bloodSlash'),JSON.stringify(result));assert.ok(result.seen.includes('authoredPose'),JSON.stringify(result));assert.equal(result.remaining,0);await game.screenshot({path:path.join(out,'game-desktop.png'),fullPage:true});checks.push('real standalone card action plays authored poses/effects and cleans up');
 await game.evaluate(async()=>{const {playCombatEffectPlan,clearCombatEffects}=await import('/src/ui/combatEffectSprites.js');const layer=document.querySelector('.fx-layer'),before=document.querySelector('.painted-stage .pose-frame').style.visibility;playCombatEffectPlan(layer,{left:0,top:0,width:230,height:350},{kind:'bloodSlash',tags:['blood','blade'],bindingContext:{provider:'ashenspire',kind:'card',event:'actionResolved',tags:['blood','blade'],staminaSpent:2}},{duration:2000});clearCombatEffects(layer);await new Promise(r=>setTimeout(r,100));if(document.querySelector('.studio-combat-effect,.studio-pose-frame'))throw Error('Custom sequence outlived cancellation');if(document.querySelector('.painted-stage .pose-frame').style.visibility!==before)throw Error('Canceled pose was not restored');});checks.push('layer clear cancels authored sequence');
 await game.evaluate(async()=>{const {playPresentationSequence}=await import('/src/ui/presentationSequence.js');const p=JSON.parse(localStorage.getItem('ashenspire.pose-studio.active.v1')),layer=document.querySelector('.fx-layer');p.anchors.target=[.8,.55];p.clips=[{...p.clips[0],cue:'anticipation',offset:0,duration:1200,anchor:'target',x:20,y:-10,travel:false}];const stop=playPresentationSequence(layer,{left:0,top:0,width:230,height:350},{provider:'ashenspire',kind:'card',event:'actionResolved',tags:['blood','blade'],staminaSpent:2},{project:p,targets:[{left:600,top:100,width:230,height:350}],duration:1000});await new Promise(r=>setTimeout(r,100));const el=layer.querySelector('.studio-combat-effect');if(!el)throw Error('Target effect missing');const x=parseFloat(el.style.left)+parseFloat(el.style.width)/2,y=parseFloat(el.style.top)+parseFloat(el.style.height)/2;if(Math.abs(x-775)>1||Math.abs(y-265)>1)throw Error('Authored target offset lost: '+x+','+y);stop();});checks.push('edited target anchor and offsets retained in game');
 await page.locator('#clear-game').click();assert.equal(await page.evaluate(()=>localStorage.getItem('ashenspire.pose-studio.active.v1')),null);checks.push('game override removal');
 assert.deepEqual(errors,[]);await writeFile(path.join(out,'checks.json'),JSON.stringify({checks,errors,game:result},null,2));console.log(JSON.stringify({checks,errors,game:result},null,2));
}finally{await browser.close();}

