// src/content/aiDisclosure.js — THE ONE HOME of the AI-use acknowledgement.
//
// Two surfaces render from this file and neither retypes it:
//   · in-product  — Settings → About (src/ui/screens/about.js)
//   · the store   — Steam's AI-disclosure field, printed by
//                   `node tools/ai-disclosure.mjs` and pasted from that output
//
// WHY IT LIVES HERE AND NOT IN A DOCUMENT. The same acknowledgement appearing
// in two places, maintained by hand, is one fact with two homes: the day they
// disagree, a player comparing the store page to the game is reading two
// different claims about the same thing and we cannot say which is true.
// So the text has one home — this file — and everything else renders it.
// `node tools/ai-disclosure.mjs --check` fails if a shipped bundle has drifted
// from this module, which is what makes that a fact rather than an intention.
//
// APPROVAL: the final wording is Constantine's call at release (`approved`
// below). An edit here lands on both surfaces in the same act, which is the
// entire point of the arrangement.
//
// Headless-safe: data only, no document, no storage, no timers.

// The load-bearing sentence gets its own name because it has two jobs: it is the
// last line a player reads, and it is the claim `tools/ai-disclosure.mjs` proves.
// It used to exist twice — once here inside `storeForm`, once paraphrased in
// `runtimeCheck.claim` — in DIFFERENT WORDS, so no comparison could ever have
// caught them diverging, and the copy with no reader was the one that would rot
// (Bjorn found it at the pixel; nothing rendered it and `--check` never bound
// it). One home now: the falsifier and the player are told the same sentence,
// because it is the same string.
const RUNTIME_CLAIM = `No AI runs while you play: nothing in the game is AI-generated at runtime, and the game contacts no AI service.`;

// The rest of the store form. Kept a separate unbroken literal so `--check` can
// bind each piece in the shipped bundle; the bundler preserves source literals,
// and an interpolation would put the template — not the text — in the bundle.
const STORE_LEAD = `Ashen Spire was built by AI under human direction. The game’s code, design, writing, and art were authored by AI assistants (Anthropic’s Claude) working under the human developer’s instruction, review, and testing. All shipped art is generated by code — the game’s own placeholder renderer and AI-written 3D rendering pipelines; no AI image-generation models were used. The soundtrack and sound effects are synthesized by AI-written code at runtime; this release ships no pre-recorded audio files, and any audio added later is itemized with its provenance in the game’s credits.`;

// THE `version` FIELD IS GONE, AND THE APPROVED WORDING BELOW IS UNTOUCHED.
//
// It held `'0.4.x'` — a hand-typed scope string, rendered on Settings → About
// while title/map/combat rendered the derived build stamp: two numbers on two
// screens, live. `tools/buildversion.mjs` row B had this listed as a second
// version site that was KNOWN AND OPEN, resolving the whole check to UNKNOWN,
// because which of the two should move was a Tier-2 call and Constantine's
// alone. He made it on 2026-08-16 — "a4 is really nice" — and A4 puts the
// derived build version on the About line. So the field has no reader left,
// and a value nobody renders is the copy this file's own header warns about.
//
// THIS IS NOT AN EDIT TO THE ACKNOWLEDGEMENT. `approved` guards the text below
// it — storeForm, sections, runtimeCheck — which is what he read and approved
// (b349bbd / #92). `version` sat above the flag, is not a word of the
// acknowledgement, and `tools/ai-disclosure.mjs --check` binds DISCLOSURE_PARTS
// (the store lead and the runtime claim), neither of which moves here. The flag
// stays `true` because the wording it is about is byte-identical.
//
// `updated` STAYS, AND IT STAYS HAND-TYPED. It is the date this wording last
// changed — a fact of the text's own history, not of the build — and nothing in
// this tree derives it. It is not made derived here rather than being given a
// plausible machine answer; see the session log.
export const AI_DISCLOSURE = Object.freeze({
  updated: '2026-08-07',

  // TRUE since 2026-08-07: Constantine approved this wording — "I approve the ai
  // disclosure." Nothing in the game reads this to decide whether to render — the
  // acknowledgement always shows. It marks whose words these are, and they are now
  // his as well as ours. Any edit to the text below returns this to `false`; the
  // flag is about THIS wording, not about disclosure in general.
  approved: true,

  /**
   * storeForm — the text pasted into Steam's AI-disclosure field, and the lead
   * paragraph of the in-product acknowledgement. ONE string, both surfaces.
   */
  // Assembled from its two parts, so the claim below and the last sentence a
  // player reads are the same string rather than two sentences that agree today.
  storeForm: `${STORE_LEAD} ${RUNTIME_CLAIM}`,

  /**
   * sections — the fuller acknowledgement, shown under the lead in-product.
   * Each is one honest answer to "what did the AI actually do here".
   */
  sections: Object.freeze([
    Object.freeze({
      heading: 'Code and design',
      body: `The engine, interface, tools, and the design specification were written by AI assistants working as a team of specialist personas, under the direction of the human developer — who set the goals, reviewed the work, played the builds, and holds final approval on everything that ships.`,
    }),
    Object.freeze({
      heading: 'Writing',
      body: `All game text — card names and rules text, interface copy, flavour — was AI-authored under that same direction.`,
    }),
    Object.freeze({
      heading: 'Art',
      body: `Every visual is generated by code. Sprites, icons and panels are drawn at runtime by the game itself; the class figures, act backdrops and equipment art are pre-rendered by procedural Blender scripts that the AI wrote. No image-generation model was used at any point — the art is rendered, and the AI-authored part is the code that renders it.`,
    }),
    Object.freeze({
      heading: 'Audio',
      body: `The score and every sound effect are synthesized as you play, by AI-written code — this release ships no audio files at all. If recorded music or effects are added in a later version, each file is listed in CREDITS with how it was made and who made it.`,
    }),
    Object.freeze({
      heading: 'While you play',
      body: `No AI model runs in this game, on your machine or anywhere else. Nothing is generated while you play, and the game never contacts an AI service. The only network features are optional local co-op and an optional folder of your own music.`,
    }),
    Object.freeze({
      heading: 'Your saves',
      body: `Your profile and runs are yours. When something cannot be read, it is set aside rather than deleted, and Settings → Profile lists everything that has been set aside — with a button to save any of it to a file. Nothing is ever deleted to make room for anything else.`,
    }),
  ]),

  /**
   * runtimeCheck — the load-bearing claim, and where its falsifier lives.
   *
   * THE COMMANDS ARE NOT IN THIS FILE, AND THAT IS DELIBERATE. This module is
   * the disclosure, so it necessarily names the AI vendor it is disclosing; and
   * a search pattern stored here would spell out every vendor and every
   * network-primitive name the pattern hunts for. Both times I tried it, our
   * own falsifier matched its own text and returned red on a clean tree —
   * first the vendor name in `storeForm`, then the pattern inside the pattern.
   * A falsifier that cannot survive being written down beside its claim belongs
   * one step away from it, outside `src/`, where what it searches cannot
   * contain it. (This comment is written the same way, on purpose: it describes
   * the trap without spelling the words that would spring it.)
   *
   * So: `tools/ai-disclosure.mjs` owns the commands, prints them verbatim
   * (`--evidence`) and runs them (`--check`). This file owns the claim.
   */
  runtimeCheck: Object.freeze({
    claim: RUNTIME_CLAIM,
    verifyWith: `node tools/ai-disclosure.mjs --evidence`,
    networkNote: `A separate grep for network primitives returns exactly two sites in the whole game, both local and neither AI: src/net/lan.js (LAN co-op against the game's own launcher) and src/ui/audio.js (the player's own configured music folder).`,
  }),
});

/** The atomic texts the bundles must carry — each an unbroken literal above. */
export const DISCLOSURE_PARTS = Object.freeze([
  Object.freeze({ name: 'store lead', text: STORE_LEAD }),
  Object.freeze({ name: 'runtime claim (also runtimeCheck.claim)', text: RUNTIME_CLAIM }),
]);

/**
 * The in-product acknowledgement as plain text — the export/copy path.
 *
 * THE VERSION IS PASSED IN AND NOT IMPORTED, and that is load-bearing rather
 * than fussy. `tools/ai-disclosure.mjs --evidence` prints, as the falsifier a
 * sceptic pastes into a terminal, that this file "imports nothing and calls
 * nothing" — it is the command that closes the hole left by excluding this file
 * from the AI-service grep. An `import` here would make that evidence false.
 * So the caller, which already knows the build, hands the version down.
 */
export function disclosureAsText(d = AI_DISCLOSURE, version = null) {
  return [
    version ? `Ashen Spire — AI use acknowledgement (${version})` : `Ashen Spire — AI use acknowledgement`,
    '',
    d.storeForm,
    '',
    ...d.sections.map((s) => `${s.heading}\n${s.body}\n`),
  ].join('\n');
}
