// Scoped ids are deliberate: two classes can wear different sets named default.
export const combatExpansionEquipment = {
  armour: {
    'reaver:default': { armorClass: 'medium', flat: { slashing: 1 }, traits: { conductive: true } },
    'reaver:vigil': { armorClass: 'medium', flat: { frost: 1 } },
    'reaver:oathsworn': { armorClass: 'medium', flat: { slashing: 1, decay: 1 }, traits: { conductive: true } },
    'reaver:warden': { armorClass: 'heavy', flat: { slashing: 2, piercing: 1 }, traits: { conductive: true } },
    'reaver:bastion': { armorClass: 'heavy', flat: { blunt: 1, slashing: 2 }, traits: { conductive: true } },
    'starseer:default': { armorClass: 'light', flat: { frost: 1 } },
    'starseer:eclipse': { armorClass: 'light', flat: { arcane: 1 }, traits: { buildupResistance: { sleep: 10 } } },
    'starseer:starlit': { armorClass: 'light', flat: { frost: 1 }, traits: { insulated: true } },
    'starseer:astral': { armorClass: 'light', flat: { arcane: 1, frost: 1 }, traits: { buildupResistance: { dazed: 10 } } },
    'starseer:rimeweave': { armorClass: 'light', flat: { frost: 2 }, traits: { buildupResistance: { frost: 15 } } },
    'herald:default': { armorClass: 'medium', flat: { decay: 1 } },
    'herald:ossuary': { armorClass: 'medium', flat: { decay: 1 }, traits: { buildupResistance: { crimsonBlight: 15 } } },
    'herald:emberhabit': { armorClass: 'light', flat: { fire: 1 }, traits: { buildupResistance: { burn: 15 } } },
    'herald:pilgrim': { armorClass: 'medium', flat: { sacred: 1 }, traits: { recoveryBonus: { curse: 5 } } },
    'rogue:default': { armorClass: 'light', flat: { piercing: 1 } },
    'rogue:nightveil': { armorClass: 'light', flat: { piercing: 1 }, traits: { buildupResistance: { sleep: 10 } } },
    'rogue:duelist': { armorClass: 'light', flat: { slashing: 1 }, traits: { recoveryBonus: { bodily: 5 } } },
    'rogue:shadow': { armorClass: 'light', flat: { piercing: 1 }, traits: { buildupResistance: { venom: 15 } } },
    'rogue:waywatcher': { armorClass: 'light', flat: { piercing: 1 }, traits: { insulated: true } },
  },
  sharedArmour: {
    wayfarerPlate: { armorClass: 'heavy', flat: { slashing: 1, piercing: 1 }, traits: { conductive: true } },
    nightweave: { armorClass: 'light', flat: { frost: 1 }, traits: { recoveryBonus: { mental: 5 } } },
    riteVestments: { armorClass: 'medium', flat: { sacred: 1 }, traits: { buildupResistance: { weak: 10 } } },
    gutterLeathers: { armorClass: 'light', flat: { piercing: 1 }, traits: { buildupResistance: { venom: 10 } } },
  },
  armaments: {
    straightSword: { traits: { conductive: true } }, greatsword: { traits: { conductive: true } },
    dagger: { traits: { conductive: true } }, katana: { traits: { conductive: true } },
    halberd: { traits: { conductive: true } }, warhammer: { traits: { conductive: true } },
    twinblade: { traits: { conductive: true } }, battleaxe: { traits: { conductive: true } },
    buckler: { flat: { piercing: 1 }, traits: { conductive: true } },
    kiteShield: { flat: { slashing: 1 }, traits: { conductive: true } },
    towerShield: { flat: { piercing: 1, slashing: 1 }, traits: { conductive: true } },
    roundShield: { flat: { piercing: 1 }, traits: { conductive: true } },
    spikedShield: { flat: { slashing: 1 }, traits: { conductive: true } },
    parryDagger: { traits: { conductive: true } }, shortbow: {},
    lantern: { flat: { decay: 1 } }, torch: { flat: { frost: 1 } },
    ashStaff: { traits: { caster: true } }, starstoneStaff: { traits: { caster: true, conductive: true } },
    boneSceptre: { traits: { caster: true } }, emberlightSceptre: { traits: { caster: true, insulated: true } },
    goldboughBranch: { traits: { caster: true, grounded: true } }, blightRod: { traits: { caster: true } },
    gorefireBrand: { traits: { caster: true, conductive: true } }, wyrmhornStaff: { traits: { caster: true, insulated: true } },
    frostSpear: { traits: { conductive: true }, flat: { frost: 1 } },
    cinderAxe: { traits: { conductive: true }, flat: { fire: 1 } }, duskChime: { traits: { caster: true, conductive: true } },
  },
  enemies: {
    wanderingSoldier: { armorClass: 'medium', weak: { blunt: 25, fire: 25 }, traits: { conductive: true } },
    blightHound: { armorClass: 'light', weak: { slashing: 25, fire: 25 } },
    huskBrute: { armorClass: 'medium', weak: { blunt: 25, sacred: 25 }, traits: { mindless: true } },
    graveWisp: { armorClass: 'light', weak: { blunt: 25, sacred: 25 }, traits: { caster: true } },
    wyrmAspirant: { armorClass: 'heavy', weak: { piercing: 25, frost: 25 }, traits: { conductive: true, caster: true } },
    fellWarden: { armorClass: 'medium', weak: { blunt: 25, sacred: 25 }, traits: { conductive: true } },
    lanternMoth: { armorClass: 'light', weak: { piercing: 25, frost: 25 }, traits: { caster: true } },
    briarHermit: { armorClass: 'light', weak: { slashing: 25, fire: 25 }, traits: { caster: true } },
    chainScavenger: { armorClass: 'medium', weak: { blunt: 25, frost: 25 }, traits: { conductive: true } },
    bellKeeper: { armorClass: 'heavy', weak: { blunt: 25, frost: 25 }, traits: { conductive: true, mindless: true } },
    thornMatriarch: { armorClass: 'medium', weak: { slashing: 25, fire: 25 }, traits: { caster: true } },
    gildedKnight: { armorClass: 'heavy', weak: { blunt: 25, decay: 25 }, traits: { conductive: true } },
    courtSurgeon: { armorClass: 'light', weak: { piercing: 25, fire: 25 }, traits: { caster: true } },
    stitchedHound: { armorClass: 'medium', weak: { slashing: 25, sacred: 25 }, traits: { mindless: true } },
    courtMarionette: { armorClass: 'light', weak: { blunt: 25, fire: 25 }, traits: { mindless: true } },
    livingArmor: { armorClass: 'heavy', flat: { slashing: 1 }, weak: { blunt: 25, frost: 25 }, traits: { conductive: true, mindless: true } },
    courtDuelist: { armorClass: 'light', weak: { blunt: 25, frost: 25 }, traits: { conductive: true } },
    stitchedKing: { armorClass: 'medium', weak: { slashing: 25, sacred: 25 }, traits: { caster: true } },
    mirrorScribe: { armorClass: 'light', weak: { blunt: 25, decay: 25 }, traits: { caster: true, conductive: true } },
    stitchCrab: { armorClass: 'heavy', weak: { blunt: 25, fire: 25 }, traits: { mindless: true } },
    glassRegent: { armorClass: 'heavy', flat: { piercing: 1 }, weak: { blunt: 25, frost: 25 }, traits: { caster: true, mindless: true } },
    marrowOrganist: { armorClass: 'light', weak: { blunt: 25, sacred: 25 }, traits: { caster: true } },
    ashRevenant: { armorClass: 'medium', weak: { blunt: 25, frost: 25 } },
    emberStarvedPilgrim: { armorClass: 'light', weak: { slashing: 25, frost: 25 } },
    valkyrieShade: { armorClass: 'light', weak: { piercing: 25, sacred: 25 }, traits: { caster: true } },
    charredColossus: { armorClass: 'heavy', flat: { slashing: 1 }, weak: { blunt: 25, frost: 25 }, traits: { mindless: true } },
    wyrmLord: { armorClass: 'heavy', weak: { piercing: 25, frost: 25 }, traits: { caster: true, conductive: true } },
    blightedValkyrie: { armorClass: 'medium', weak: { piercing: 25, sacred: 25 }, traits: { caster: true } },
    cinderMantis: { armorClass: 'light', weak: { blunt: 25, frost: 25 } },
    eclipseCantor: { armorClass: 'light', weak: { slashing: 25, sacred: 25 }, traits: { caster: true } },
    furnaceSaint: { armorClass: 'heavy', weak: { blunt: 25, frost: 25 }, traits: { conductive: true, mindless: true } },
    hollowAstronomer: { armorClass: 'light', weak: { piercing: 25, sacred: 25 }, traits: { caster: true } },
    ashheartDragon: { armorClass: 'heavy', flat: { slashing: 1 }, weak: { piercing: 25, frost: 25 }, traits: { caster: true } },
  },
};
