// Generated by tools/painted-outfits-ship.mjs.
export const PAINTED_OUTFITS = {
  "rogue": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/rogue/idle.webp",
        "box": {
          "x0": 216,
          "x1": 432,
          "y0": 324,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/rogue/guard.webp",
        "box": {
          "x0": 216,
          "x1": 432,
          "y0": 324,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/rogue/attack1.webp",
        "box": {
          "x0": 202,
          "x1": 489,
          "y0": 325,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/rogue/attack2.webp",
        "box": {
          "x0": 241,
          "x1": 609,
          "y0": 370,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/rogue/attack3.webp",
        "box": {
          "x0": 210,
          "x1": 512,
          "y0": 347,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/rogue/attack4.webp",
        "box": {
          "x0": 211,
          "x1": 558,
          "y0": 405,
          "y1": 601
        }
      },
      "hit": {
        "file": "assets/painted-outfits/rogue/hit.webp",
        "box": {
          "x0": 155,
          "x1": 398,
          "y0": 324,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/rogue/menu.webp",
      "detail": "assets/painted-outfits/rogue/detail.webp",
      "portrait": "assets/painted-outfits/rogue/portrait.webp"
    }
  },
  "rogue-nightveil": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/rogue-nightveil/idle.webp",
        "box": {
          "x0": 171,
          "x1": 431,
          "y0": 291,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/rogue-nightveil/guard.webp",
        "box": {
          "x0": 171,
          "x1": 431,
          "y0": 291,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/rogue-nightveil/attack1.webp",
        "box": {
          "x0": 200,
          "x1": 513,
          "y0": 314,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/rogue-nightveil/attack2.webp",
        "box": {
          "x0": 216,
          "x1": 610,
          "y0": 343,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/rogue-nightveil/attack3.webp",
        "box": {
          "x0": 193,
          "x1": 524,
          "y0": 342,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/rogue-nightveil/attack4.webp",
        "box": {
          "x0": 175,
          "x1": 451,
          "y0": 334,
          "y1": 601
        }
      },
      "hit": {
        "file": "assets/painted-outfits/rogue-nightveil/hit.webp",
        "box": {
          "x0": 158,
          "x1": 477,
          "y0": 259,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/rogue-nightveil/menu.webp",
      "detail": "assets/painted-outfits/rogue-nightveil/detail.webp",
      "portrait": "assets/painted-outfits/rogue-nightveil/portrait.webp"
    }
  },
  "rogue-duelist": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/rogue-duelist/idle.webp",
        "box": {
          "x0": 221,
          "x1": 484,
          "y0": 317,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/rogue-duelist/guard.webp",
        "box": {
          "x0": 221,
          "x1": 484,
          "y0": 317,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/rogue-duelist/attack1.webp",
        "box": {
          "x0": 210,
          "x1": 586,
          "y0": 331,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/rogue-duelist/attack2.webp",
        "box": {
          "x0": 198,
          "x1": 611,
          "y0": 341,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/rogue-duelist/attack3.webp",
        "box": {
          "x0": 201,
          "x1": 541,
          "y0": 320,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/rogue-duelist/attack4.webp",
        "box": {
          "x0": 220,
          "x1": 503,
          "y0": 331,
          "y1": 601
        }
      },
      "hit": {
        "file": "assets/painted-outfits/rogue-duelist/hit.webp",
        "box": {
          "x0": 208,
          "x1": 442,
          "y0": 325,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/rogue-duelist/menu.webp",
      "detail": "assets/painted-outfits/rogue-duelist/detail.webp",
      "portrait": "assets/painted-outfits/rogue-duelist/portrait.webp"
    }
  },
  "rogue-shadow": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/rogue-shadow/idle.webp",
        "box": {
          "x0": 202,
          "x1": 447,
          "y0": 305,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/rogue-shadow/guard.webp",
        "box": {
          "x0": 202,
          "x1": 447,
          "y0": 305,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/rogue-shadow/attack1.webp",
        "box": {
          "x0": 213,
          "x1": 524,
          "y0": 306,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/rogue-shadow/attack2.webp",
        "box": {
          "x0": 217,
          "x1": 566,
          "y0": 340,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/rogue-shadow/attack3.webp",
        "box": {
          "x0": 197,
          "x1": 510,
          "y0": 320,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/rogue-shadow/attack4.webp",
        "box": {
          "x0": 200,
          "x1": 466,
          "y0": 335,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/rogue-shadow/hit.webp",
        "box": {
          "x0": 185,
          "x1": 463,
          "y0": 295,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/rogue-shadow/menu.webp",
      "detail": "assets/painted-outfits/rogue-shadow/detail.webp",
      "portrait": "assets/painted-outfits/rogue-shadow/portrait.webp"
    }
  },
  "reaver": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/reaver/idle.webp",
        "box": {
          "x0": 221,
          "x1": 417,
          "y0": 260,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/reaver/guard.webp",
        "box": {
          "x0": 187,
          "x1": 566,
          "y0": 261,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/reaver/attack1.webp",
        "box": {
          "x0": 197,
          "x1": 516,
          "y0": 343,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/reaver/attack2.webp",
        "box": {
          "x0": 146,
          "x1": 453,
          "y0": 240,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/reaver/attack3.webp",
        "box": {
          "x0": 62,
          "x1": 477,
          "y0": 361,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/reaver/attack4.webp",
        "box": {
          "x0": 171,
          "x1": 554,
          "y0": 314,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/reaver/hit.webp",
        "box": {
          "x0": 164,
          "x1": 504,
          "y0": 252,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/reaver/menu.webp",
      "detail": "assets/painted-outfits/reaver/detail.webp",
      "portrait": "assets/painted-outfits/reaver/portrait.webp"
    }
  },
  "reaver-vigil": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/reaver-vigil/idle.webp",
        "box": {
          "x0": 196,
          "x1": 422,
          "y0": 260,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/reaver-vigil/guard.webp",
        "box": {
          "x0": 175,
          "x1": 558,
          "y0": 260,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/reaver-vigil/attack1.webp",
        "box": {
          "x0": 151,
          "x1": 512,
          "y0": 350,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/reaver-vigil/attack2.webp",
        "box": {
          "x0": 162,
          "x1": 472,
          "y0": 248,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/reaver-vigil/attack3.webp",
        "box": {
          "x0": 89,
          "x1": 498,
          "y0": 361,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/reaver-vigil/attack4.webp",
        "box": {
          "x0": 164,
          "x1": 489,
          "y0": 370,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/reaver-vigil/hit.webp",
        "box": {
          "x0": 173,
          "x1": 520,
          "y0": 250,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/reaver-vigil/menu.webp",
      "detail": "assets/painted-outfits/reaver-vigil/detail.webp",
      "portrait": "assets/painted-outfits/reaver-vigil/portrait.webp"
    }
  },
  "reaver-oathsworn": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/reaver-oathsworn/idle.webp",
        "box": {
          "x0": 222,
          "x1": 408,
          "y0": 261,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/reaver-oathsworn/guard.webp",
        "box": {
          "x0": 192,
          "x1": 553,
          "y0": 261,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/reaver-oathsworn/attack1.webp",
        "box": {
          "x0": 184,
          "x1": 509,
          "y0": 369,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/reaver-oathsworn/attack2.webp",
        "box": {
          "x0": 163,
          "x1": 452,
          "y0": 261,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/reaver-oathsworn/attack3.webp",
        "box": {
          "x0": 125,
          "x1": 455,
          "y0": 382,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/reaver-oathsworn/attack4.webp",
        "box": {
          "x0": 198,
          "x1": 466,
          "y0": 305,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/reaver-oathsworn/hit.webp",
        "box": {
          "x0": 177,
          "x1": 514,
          "y0": 264,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/reaver-oathsworn/menu.webp",
      "detail": "assets/painted-outfits/reaver-oathsworn/detail.webp",
      "portrait": "assets/painted-outfits/reaver-oathsworn/portrait.webp"
    }
  },
  "reaver-warden": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/reaver-warden/idle.webp",
        "box": {
          "x0": 206,
          "x1": 414,
          "y0": 260,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/reaver-warden/guard.webp",
        "box": {
          "x0": 193,
          "x1": 546,
          "y0": 261,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/reaver-warden/attack1.webp",
        "box": {
          "x0": 194,
          "x1": 520,
          "y0": 358,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/reaver-warden/attack2.webp",
        "box": {
          "x0": 162,
          "x1": 460,
          "y0": 269,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/reaver-warden/attack3.webp",
        "box": {
          "x0": 120,
          "x1": 468,
          "y0": 391,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/reaver-warden/attack4.webp",
        "box": {
          "x0": 187,
          "x1": 445,
          "y0": 322,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/reaver-warden/hit.webp",
        "box": {
          "x0": 172,
          "x1": 528,
          "y0": 253,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/reaver-warden/menu.webp",
      "detail": "assets/painted-outfits/reaver-warden/detail.webp",
      "portrait": "assets/painted-outfits/reaver-warden/portrait.webp"
    }
  },
  "starseer": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/starseer/idle.webp",
        "box": {
          "x0": 239,
          "x1": 422,
          "y0": 260,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/starseer/guard.webp",
        "box": {
          "x0": 217,
          "x1": 455,
          "y0": 318,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/starseer/attack1.webp",
        "box": {
          "x0": 197,
          "x1": 471,
          "y0": 338,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/starseer/attack2.webp",
        "box": {
          "x0": 224,
          "x1": 531,
          "y0": 365,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/starseer/attack3.webp",
        "box": {
          "x0": 216,
          "x1": 548,
          "y0": 386,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/starseer/attack4.webp",
        "box": {
          "x0": 233,
          "x1": 549,
          "y0": 363,
          "y1": 601
        }
      },
      "hit": {
        "file": "assets/painted-outfits/starseer/hit.webp",
        "box": {
          "x0": 225,
          "x1": 433,
          "y0": 349,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/starseer/menu.webp",
      "detail": "assets/painted-outfits/starseer/detail.webp",
      "portrait": "assets/painted-outfits/starseer/portrait.webp"
    }
  },
  "starseer-eclipse": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/starseer-eclipse/idle.webp",
        "box": {
          "x0": 201,
          "x1": 458,
          "y0": 260,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/starseer-eclipse/guard.webp",
        "box": {
          "x0": 197,
          "x1": 451,
          "y0": 301,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/starseer-eclipse/attack1.webp",
        "box": {
          "x0": 179,
          "x1": 471,
          "y0": 284,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/starseer-eclipse/attack2.webp",
        "box": {
          "x0": 190,
          "x1": 539,
          "y0": 302,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/starseer-eclipse/attack3.webp",
        "box": {
          "x0": 193,
          "x1": 567,
          "y0": 321,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/starseer-eclipse/attack4.webp",
        "box": {
          "x0": 139,
          "x1": 501,
          "y0": 335,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/starseer-eclipse/hit.webp",
        "box": {
          "x0": 202,
          "x1": 447,
          "y0": 324,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/starseer-eclipse/menu.webp",
      "detail": "assets/painted-outfits/starseer-eclipse/detail.webp",
      "portrait": "assets/painted-outfits/starseer-eclipse/portrait.webp"
    }
  },
  "starseer-starlit": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/starseer-starlit/idle.webp",
        "box": {
          "x0": 193,
          "x1": 449,
          "y0": 261,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/starseer-starlit/guard.webp",
        "box": {
          "x0": 196,
          "x1": 499,
          "y0": 299,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/starseer-starlit/attack1.webp",
        "box": {
          "x0": 201,
          "x1": 481,
          "y0": 298,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/starseer-starlit/attack2.webp",
        "box": {
          "x0": 207,
          "x1": 541,
          "y0": 300,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/starseer-starlit/attack3.webp",
        "box": {
          "x0": 223,
          "x1": 566,
          "y0": 298,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/starseer-starlit/attack4.webp",
        "box": {
          "x0": 180,
          "x1": 508,
          "y0": 289,
          "y1": 601
        }
      },
      "hit": {
        "file": "assets/painted-outfits/starseer-starlit/hit.webp",
        "box": {
          "x0": 197,
          "x1": 495,
          "y0": 318,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/starseer-starlit/menu.webp",
      "detail": "assets/painted-outfits/starseer-starlit/detail.webp",
      "portrait": "assets/painted-outfits/starseer-starlit/portrait.webp"
    }
  },
  "starseer-astral": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/starseer-astral/idle.webp",
        "box": {
          "x0": 199,
          "x1": 453,
          "y0": 260,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/starseer-astral/guard.webp",
        "box": {
          "x0": 207,
          "x1": 489,
          "y0": 299,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/starseer-astral/attack1.webp",
        "box": {
          "x0": 210,
          "x1": 453,
          "y0": 231,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/starseer-astral/attack2.webp",
        "box": {
          "x0": 199,
          "x1": 563,
          "y0": 325,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/starseer-astral/attack3.webp",
        "box": {
          "x0": 219,
          "x1": 596,
          "y0": 336,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/starseer-astral/attack4.webp",
        "box": {
          "x0": 203,
          "x1": 562,
          "y0": 320,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/starseer-astral/hit.webp",
        "box": {
          "x0": 163,
          "x1": 480,
          "y0": 296,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/starseer-astral/menu.webp",
      "detail": "assets/painted-outfits/starseer-astral/detail.webp",
      "portrait": "assets/painted-outfits/starseer-astral/portrait.webp"
    }
  },
  "herald": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/herald/idle.webp",
        "box": {
          "x0": 253,
          "x1": 386,
          "y0": 260,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/herald/guard.webp",
        "box": {
          "x0": 195,
          "x1": 466,
          "y0": 293,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/herald/attack1.webp",
        "box": {
          "x0": 181,
          "x1": 468,
          "y0": 309,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/herald/attack2.webp",
        "box": {
          "x0": 188,
          "x1": 525,
          "y0": 316,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/herald/attack3.webp",
        "box": {
          "x0": 194,
          "x1": 556,
          "y0": 318,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/herald/attack4.webp",
        "box": {
          "x0": 197,
          "x1": 483,
          "y0": 316,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/herald/hit.webp",
        "box": {
          "x0": 206,
          "x1": 418,
          "y0": 310,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/herald/menu.webp",
      "detail": "assets/painted-outfits/herald/detail.webp",
      "portrait": "assets/painted-outfits/herald/portrait.webp"
    }
  },
  "herald-ossuary": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/herald-ossuary/idle.webp",
        "box": {
          "x0": 217,
          "x1": 425,
          "y0": 260,
          "y1": 600
        }
      },
      "guard": {
        "file": "assets/painted-outfits/herald-ossuary/guard.webp",
        "box": {
          "x0": 217,
          "x1": 426,
          "y0": 298,
          "y1": 600
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/herald-ossuary/attack1.webp",
        "box": {
          "x0": 215,
          "x1": 456,
          "y0": 291,
          "y1": 600
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/herald-ossuary/attack2.webp",
        "box": {
          "x0": 212,
          "x1": 495,
          "y0": 294,
          "y1": 600
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/herald-ossuary/attack3.webp",
        "box": {
          "x0": 215,
          "x1": 544,
          "y0": 294,
          "y1": 600
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/herald-ossuary/attack4.webp",
        "box": {
          "x0": 210,
          "x1": 482,
          "y0": 294,
          "y1": 600
        }
      },
      "hit": {
        "file": "assets/painted-outfits/herald-ossuary/hit.webp",
        "box": {
          "x0": 211,
          "x1": 429,
          "y0": 291,
          "y1": 600
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/herald-ossuary/menu.webp",
      "detail": "assets/painted-outfits/herald-ossuary/detail.webp",
      "portrait": "assets/painted-outfits/herald-ossuary/portrait.webp"
    }
  },
  "herald-emberhabit": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/herald-emberhabit/idle.webp",
        "box": {
          "x0": 209,
          "x1": 441,
          "y0": 261,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/herald-emberhabit/guard.webp",
        "box": {
          "x0": 208,
          "x1": 444,
          "y0": 292,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/herald-emberhabit/attack1.webp",
        "box": {
          "x0": 210,
          "x1": 468,
          "y0": 294,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/herald-emberhabit/attack2.webp",
        "box": {
          "x0": 204,
          "x1": 510,
          "y0": 308,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/herald-emberhabit/attack3.webp",
        "box": {
          "x0": 210,
          "x1": 540,
          "y0": 311,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/herald-emberhabit/attack4.webp",
        "box": {
          "x0": 204,
          "x1": 496,
          "y0": 315,
          "y1": 601
        }
      },
      "hit": {
        "file": "assets/painted-outfits/herald-emberhabit/hit.webp",
        "box": {
          "x0": 210,
          "x1": 433,
          "y0": 303,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/herald-emberhabit/menu.webp",
      "detail": "assets/painted-outfits/herald-emberhabit/detail.webp",
      "portrait": "assets/painted-outfits/herald-emberhabit/portrait.webp"
    }
  },
  "herald-pilgrim": {
    "frames": {
      "idle": {
        "file": "assets/painted-outfits/herald-pilgrim/idle.webp",
        "box": {
          "x0": 221,
          "x1": 427,
          "y0": 261,
          "y1": 601
        }
      },
      "guard": {
        "file": "assets/painted-outfits/herald-pilgrim/guard.webp",
        "box": {
          "x0": 204,
          "x1": 426,
          "y0": 298,
          "y1": 601
        }
      },
      "attack1": {
        "file": "assets/painted-outfits/herald-pilgrim/attack1.webp",
        "box": {
          "x0": 207,
          "x1": 473,
          "y0": 300,
          "y1": 601
        }
      },
      "attack2": {
        "file": "assets/painted-outfits/herald-pilgrim/attack2.webp",
        "box": {
          "x0": 220,
          "x1": 547,
          "y0": 312,
          "y1": 601
        }
      },
      "attack3": {
        "file": "assets/painted-outfits/herald-pilgrim/attack3.webp",
        "box": {
          "x0": 225,
          "x1": 473,
          "y0": 310,
          "y1": 601
        }
      },
      "attack4": {
        "file": "assets/painted-outfits/herald-pilgrim/attack4.webp",
        "box": {
          "x0": 226,
          "x1": 457,
          "y0": 312,
          "y1": 601
        }
      },
      "hit": {
        "file": "assets/painted-outfits/herald-pilgrim/hit.webp",
        "box": {
          "x0": 231,
          "x1": 416,
          "y0": 330,
          "y1": 601
        }
      }
    },
    "menu": {
      "stand": "assets/painted-outfits/herald-pilgrim/menu.webp",
      "detail": "assets/painted-outfits/herald-pilgrim/detail.webp",
      "portrait": "assets/painted-outfits/herald-pilgrim/portrait.webp"
    }
  }
};
