import {starter,clone,title,CUES,ANCHORS,history,sample,startTime,validate,resolveBindings} from './model.mjs';
import {catalog,effectFrames,PAINTED_OUTFITS,labels,cards,cardContext} from './catalog.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='ashenspire.pose-studio.draft.v1',GAME_KEY='ashenspire.pose-studio.active.v1';
let initial=starter(),loadWarning='';try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&!validate(saved,catalog).length)initial=saved;}catch{loadWarning='The saved draft could not be read. A fresh project is open.';}
let stack=history(initial),project=stack.value,selected=project.clips[0]?.id,binding=project.bindings[0]?.id,time=700,playing=false,last=0,drag=null;
const images=new Map(),canvas=$('#stage'),ctx=canvas.getContext('2d');
const status=text=>$('#status').textContent=text;
function image(src){const key=project.assets[src]||new URL('../'+src,import.meta.url).href;if(!images.has(key)){const img=new Image();img.onload=draw;img.onerror=()=>status('Image unavailable: '+src);img.src=key;images.set(key,img);}return images.get(key);}
function saveDraft(){try{localStorage.setItem(KEY,JSON.stringify(project));$('#save-state').textContent='● Draft saved';}catch{$('#save-state').textContent='Draft storage full';status('Browser storage is full. Save a package to keep these changes.');}}
function change(fn,message='Draft saved.'){const next=clone(project);fn(next);const errors=validate(next,catalog);if(errors.length){status(errors.join(' · '));return false;}stack.set(next);project=stack.value;saveDraft();render();status(message);return true;}
function replace(next,message){const errors=validate(next,catalog);if(errors.length){status(errors.join(' · '));return;}stack.set(next);project=stack.value;selected=project.clips[0]?.id;binding=project.bindings[0]?.id;time=Math.min(700,project.duration);saveDraft();render();status(message);}
const chosen=()=>project.clips.find(c=>c.id===selected);
const names=id=>labels[id]||title(id);
const options=(values,current,label=title)=>values.map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label(v))}</option>`).join('');
const stop=()=>{playing=false;$('#play').textContent='▶ Play';};
function setTime(t){time=Math.max(0,Math.min(project.duration,t));$('#scrub').value=time;$('#clock').textContent=(time/1000).toFixed(2)+' s';draw();document.querySelectorAll('.pose-cell').forEach((el,i)=>el.classList.toggle('active',i===sample(project,time).poseIndex));}
function addEffect(effect,position=null,cue=null){stop();const id='clip.'+crypto.randomUUID();change(p=>{p.clips.push({id,effect,cue:cue||'anticipation',offset:cue?0:Math.round(time),duration:Math.min(420,p.duration),anchor:position?'ground':'weapon',x:position?Math.round((position[0]-p.anchors.ground[0])*1000):0,y:position?Math.round((position[1]-p.anchors.ground[1])*600):0,size:160,rotation:0,opacity:.85,layer:'front',travel:false,muted:false});selected=id;},names(effect)+' added. Drag it on stage or use Position in the inspector.');}
function library(){const query=$('#search').value.toLowerCase(),filter=$('#filter').value;const items=catalog.effects.filter(id=>(id+' '+names(id)).toLowerCase().includes(query)&&(filter==='all'||filter==='new'&&labels[id]||filter==='guard'&&/guard|ward|barrier|shield|parry|absorb/i.test(id)||filter==='aura'&&/aura|stance/i.test(id)));$('#count').textContent=catalog.effects.length;$('#effects').innerHTML=items.map(id=>`<button class="effect ${labels[id]?'new':''} ${chosen()?.effect===id?'selected':''}" draggable="true" data-effect="${esc(id)}" title="Add ${esc(names(id))}"><img src="../${effectFrames[id][2]}" alt="" loading="lazy"><span>${esc(names(id))}</span></button>`).join('');}
function render(){
 $('#name').value=project.name;$('#actor').innerHTML=options(catalog.actors,project.actor);$('#duration').value=project.duration;$('#pose-count').value=project.poses.length;$('#scrub').max=project.duration;$('#undo').disabled=!stack.canUndo;$('#redo').disabled=!stack.canRedo;
 $('#poses').style.setProperty('--frames',project.poses.length);$('#poses').innerHTML=project.poses.map((pose,i)=>`<div class="pose-cell" data-pose-slot="${i}"><button data-seek-pose="${i}" aria-label="Select pose ${i+1}"><img src="${project.assets['pose:'+pose]||'../'+PAINTED_OUTFITS[project.actor].frames[pose]?.file}" alt="Pose ${i+1}"></button><select data-pose="${i}" aria-label="Pose frame ${i+1}">${options([...catalog.poses(project.actor),...Object.keys(project.assets).filter(k=>k.startsWith('pose:')).map(k=>k.slice(5))],pose)}</select></div>`).join('');
 $('#cues').innerHTML=Object.entries(CUES).map(([cue,f])=>`<button data-cue="${cue}" style="left:${f*100}%">◆ ${title(cue)}</button>`).join('');
 $('#tracks').innerHTML=['behind','front','aura'].map(layer=>`<div class="track"><span class="track-label">${title(layer)}</span><div class="track-lane" data-layer="${layer}">${project.clips.filter(c=>c.layer===layer).map(c=>`<button draggable="true" class="clip ${c.id===selected?'selected':''}" data-clip="${esc(c.id)}" style="left:${Math.max(0,startTime(c,project)/project.duration*100)}%;width:${Math.max(3,Math.min(c.duration/project.duration*100,100-Math.max(0,startTime(c,project)/project.duration*100)))}%" title="${esc(names(c.effect))}${c.muted?' (muted)':''}">${c.muted?'○ ':''}${esc(names(c.effect))}</button>`).join('')}</div></div>`).join('');
 inspector();renderBindings();renderGraph();library();setTime(time);
}
function field(label,key,value,type='number',extra=''){return `<label>${label}<input data-field="${key}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function inspector(){const c=chosen();$('#selection').textContent=c?names(c.effect):'No effect selected';if(!c){$('#inspect').innerHTML='<p class="muted">Choose an effect from the library to begin.</p>';return;}
 $('#inspect').innerHTML=`<div class="form-grid"><label class="wide">Attach to<select data-field="anchor">${options(Object.keys(ANCHORS),c.anchor)}</select></label><label>Cue<select data-field="cue">${options(Object.keys(CUES),c.cue)}</select></label>${field('Offset · ms','offset',c.offset)}${field('Duration · ms','duration',c.duration,'number','min="60" max="30000"')}${field('Size','size',c.size,'number','min="20" max="800"')}${field('Position X','x',c.x)}${field('Position Y','y',c.y)}${field('Rotation °','rotation',c.rotation,'number','min="-360" max="360"')}${field('Opacity','opacity',c.opacity,'number','min="0" max="1" step="0.05"')}<label class="wide">Layer<select data-field="layer">${options(['behind','front','aura'],c.layer)}</select></label></div><label class="check"><input data-field="travel" type="checkbox" ${c.travel?'checked':''}> Travel to target</label><label class="check"><input data-field="muted" type="checkbox" ${c.muted?'checked':''}> Mute this effect</label><div class="button-row"><button id="duplicate">Duplicate</button><button id="remove">Remove</button></div><p class="muted" style="margin-top:12px">Starts ${(startTime(c,project)/1000).toFixed(2)} s · ${startTime(c,project)+c.duration>project.duration?'extends past the loop; increase Length to see its tail':'six distinct frames'}</p>`;
}
function drawCharacter(actor,pose,x,base,height,alpha=1){const art=PAINTED_OUTFITS[actor];const imported=project.assets['pose:'+pose],frame=art.frames[pose]||art.frames.idle;const img=imported?image('pose:'+pose):image(frame.file);if(!img.complete||!img.naturalWidth)return;ctx.save();ctx.globalAlpha=alpha;
 const aura=$('#aura').value,colors={guard:'#99c9db',mana:'#648bdc',stamina:'#95c077',hp:'#cc7474'};if(alpha===1&&colors[aura]){ctx.shadowColor=colors[aura];ctx.shadowBlur=7;}
 if(imported)ctx.drawImage(img,x-height/2,base-height,height,height);else {const scale=height/(600-art.frames.idle.box.y0);ctx.drawImage(img,x-320*scale,base-600*scale,640*scale,640*scale);}ctx.restore();}
function draw(){if(!ctx)return;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const bg=ctx.createRadialGradient(460,430,10,480,280,600);bg.addColorStop(0,'#364335');bg.addColorStop(.6,'#202d26');bg.addColorStop(1,'#15211e');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#435244';ctx.lineWidth=1;for(let i=1;i<6;i++){ctx.beginPath();ctx.moveTo(0,i*100);ctx.lineTo(w,i*100);ctx.stroke();}for(let i=1;i<10;i++){ctx.beginPath();ctx.moveTo(i*100,0);ctx.lineTo(i*100,h);ctx.stroke();}ctx.fillStyle='#101b1680';ctx.beginPath();ctx.ellipse(300,518,125,15,0,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(760,518,90,12,0,0,7);ctx.fill();
 ctx.save();if($('#direction').value==='left'){ctx.translate(w,0);ctx.scale(-1,1);}
 const result=sample(project,time,{reducedMotion:$('#reduced').checked,reduceFlashes:$('#flashes').checked});
 const drawEffect=c=>{const img=image(effectFrames[c.effect][c.frame]);if(!img.complete||!img.naturalWidth)return;ctx.save();ctx.translate(c.x*w,c.y*h);ctx.rotate(c.rotation*Math.PI/180);ctx.globalAlpha=c.opacity;ctx.drawImage(img,-c.size/2,-c.size/2,c.size,c.size);if(c.id===selected){ctx.globalAlpha=.8;ctx.strokeStyle='#d0e8ac';ctx.setLineDash([5,5]);ctx.strokeRect(-c.size/2,-c.size/2,c.size,c.size);}ctx.restore();};
 result.effects.filter(c=>c.layer==='behind'||c.layer==='aura').forEach(drawEffect);drawCharacter('starseer','guard',760,510,260,.5);drawCharacter(project.actor,result.pose,300,510,350);result.effects.filter(c=>c.layer==='front').forEach(drawEffect);
 if($('#anchors').checked){ctx.font='11px Segoe UI';for(const [key,[x,y]]of Object.entries(project.anchors)){ctx.strokeStyle='#a8c48c99';ctx.fillStyle='#c3d1b8';ctx.beginPath();ctx.arc(x*w,y*h,5,0,7);ctx.stroke();ctx.fillText(key,x*w+9,y*h-7);}}
 ctx.restore();ctx.fillStyle='#b8c6ac';ctx.font='12px Segoe UI';ctx.fillText(title(project.actor)+' · '+title(result.pose),25,570);ctx.fillText('TARGET',740,555);
}
function renderBindings(){if(!project.bindings.find(b=>b.id===binding))binding=project.bindings[0]?.id;$('#binding-list').innerHTML=project.bindings.map(b=>`<button data-binding="${esc(b.id)}" class="${b.id===binding?'selected':''}">${esc(b.name)}</button>`).join('');const b=project.bindings.find(b=>b.id===binding);$('#binding-form').innerHTML=b?`<div class="form-grid">${['name','provider','kind','objectId','event'].map(k=>`<label>${({objectId:'Exact object ID · blank matches any',kind:'Object kind · or any'})[k]||title(k)}<input data-binding-field="${k}" value="${esc(b[k])}"></label>`).join('')}${['all','any','none'].map(k=>`<label>${({all:'All these tags',any:'Any of these tags',none:'Exclude these tags'})[k]}<input data-binding-field="${k}" value="${esc(b[k].join(', '))}"></label>`).join('')}<label>Payment<select data-binding-field="resource">${options(['any','mundane','highAction','mana','stamina','resource'],b.resource)}</select></label><label>Priority<input data-binding-field="priority" type="number" min="-999" max="999" value="${b.priority}"></label></div><div class="button-row"><label><input data-binding-field="enabled" type="checkbox" ${b.enabled?'checked':''}> Enabled</label><button id="delete-binding">Delete rule</button></div>`:'<p>Add a rule to connect this sequence to a game event.</p>';testBindings();}
function context(){return {provider:$('#test-provider').value,kind:$('#test-kind').value,objectId:$('#test-object').value,event:$('#test-event').value,tags:tags($('#test-tags').value),energySpent:Number($('#test-actions').value),manaSpent:Number($('#test-mana').value),staminaSpent:Number($('#test-stamina').value)};}
const tags=text=>text.split(',').map(s=>s.trim().replace(/^fx:/,'')).filter(Boolean);
function testBindings(){const resolved=resolveBindings(project,context());$('#resolution').className=resolved.conflict?'conflict':'';$('#resolution').innerHTML=`<strong>${resolved.conflict?'Conflicting rules · choose different priorities':resolved.winner?'Matched: '+esc(resolved.winner.name):'No matching rule'}</strong><ul>${resolved.rows.map(r=>`<li>${esc(r.name)} — ${r.match?'matches (priority '+r.score+')':esc(r.reasons.join('; '))}</li>`).join('')}</ul><p class="muted">Exact object bindings outrank general selectors. Equal-priority matches are blocked. Existing game effects and auras are preserved.</p>`;}
function renderGraph(){$('#graph').innerHTML=project.bindings.map(b=>`<div class="relation-row"><div class="node"><small>${esc(b.provider)} / ${esc(b.kind)}</small>${esc(b.objectId||'Any matching object')}<small>${esc([...b.all,...b.any].join(' + ')||'No tag restriction')}</small></div><span>→</span><button class="node" data-edit-binding="${esc(b.id)}">${esc(b.name)}<small>${esc(b.event)}</small></button><span>→</span><div class="node">${esc(project.name)}<small>${project.poses.length} poses · ${project.clips.length} effects</small></div></div>`).join('')||'<p class="muted">Add a binding to see its relationships.</p>';$('#manifest').textContent=JSON.stringify({schemaVersion:project.schemaVersion,id:project.id,dependencies:['ashenspire.effects','pose-studio.effects.v1'],bindings:project.bindings.length,clips:project.clips.length,providers:[...new Set(project.bindings.map(b=>b.provider))]},null,2);}
function tab(id){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));for(const name of ['compose','bindings','relations'])$('#'+name).hidden=name!==id;}
$('#effects').onclick=e=>{const b=e.target.closest('[data-effect]');if(b)addEffect(b.dataset.effect);};$('#effects').ondragstart=e=>{const b=e.target.closest('[data-effect]');if(b)e.dataTransfer.setData('application/x-pose-effect',b.dataset.effect);};
$('#search').oninput=library;$('#filter').onchange=library;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('#inspect').onchange=e=>{const k=e.target.dataset.field;if(!k)return;const value=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.value;change(p=>{p.clips.find(c=>c.id===selected)[k]=value;});};
$('#inspect').onclick=e=>{if(e.target.id==='remove')change(p=>{p.clips=p.clips.filter(c=>c.id!==selected);selected=p.clips[0]?.id;});if(e.target.id==='duplicate'){const c=clone(chosen());c.id='clip.'+crypto.randomUUID();c.offset+=50;change(p=>{p.clips.push(c);selected=c.id;});}};
$('#name').onchange=e=>change(p=>{p.name=e.target.value;});$('#actor').onchange=e=>change(p=>{p.actor=e.target.value;p.poses=p.poses.map(pose=>catalog.poses(p.actor).includes(pose)?pose:'idle');});$('#duration').onchange=e=>change(p=>{p.duration=Number(e.target.value);time=Math.min(time,p.duration);});$('#pose-count').onchange=e=>change(p=>{const count=Number(e.target.value);p.poses=Array.from({length:count},(_,i)=>p.poses[Math.round(i*(p.poses.length-1)/(count-1))]);});
$('#poses').onchange=e=>{if(e.target.dataset.pose!==undefined)change(p=>{p.poses[Number(e.target.dataset.pose)]=e.target.value;});};$('#poses').onclick=e=>{const b=e.target.closest('[data-seek-pose]');if(b){stop();setTime(Number(b.dataset.seekPose)*project.duration/project.poses.length);}};
$('#tracks').onclick=e=>{const b=e.target.closest('[data-clip]');if(b){selected=b.dataset.clip;stop();time=Math.max(0,startTime(chosen(),project)+chosen().duration*.45);render();}};
$('#tracks').ondragstart=e=>{const b=e.target.closest('[data-clip]');if(b)e.dataTransfer.setData('application/x-pose-clip',b.dataset.clip);};
function point(e){const b=canvas.getBoundingClientRect();let x=(e.clientX-b.left)/b.width;if($('#direction').value==='left')x=1-x;return [Math.max(0,Math.min(1,x)),Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))];}
for(const element of [canvas,$('#poses'),$('#tracks'),$('#cues')]){element.ondragover=e=>e.preventDefault();element.ondrop=e=>{e.preventDefault();const effect=e.dataTransfer.getData('application/x-pose-effect'),clipId=e.dataTransfer.getData('application/x-pose-clip'),slot=e.target.closest('[data-pose-slot]'),cue=e.target.closest('[data-cue]')?.dataset.cue,lane=e.target.closest('[data-layer]');if(slot)setTime(Number(slot.dataset.poseSlot)*project.duration/project.poses.length);if(effect&&catalog.effects.includes(effect))addEffect(effect,element===canvas?point(e):null,cue);if(clipId&&lane){const box=lane.getBoundingClientRect();change(p=>{const c=p.clips.find(c=>c.id===clipId);if(c){c.layer=lane.dataset.layer;c.cue='anticipation';c.offset=Math.round(Math.max(0,Math.min(.98,(e.clientX-box.left)/box.width))*p.duration);}});}};}
canvas.onpointerdown=e=>{stop();const pt=point(e),active=sample(project,time).effects;const hit=[...active].reverse().find(c=>Math.abs(c.x-pt[0])*1000<c.size/2&&Math.abs(c.y-pt[1])*600<c.size/2);if(hit){selected=hit.id;drag={type:'effect',before:clone(project),pt};}else if($('#anchors').checked){const anchor=Object.keys(project.anchors).find(k=>Math.hypot((project.anchors[k][0]-pt[0])*1000,(project.anchors[k][1]-pt[1])*600)<16);if(anchor)drag={type:'anchor',key:anchor,before:clone(project),pt};}if(drag){canvas.setPointerCapture(e.pointerId);inspector();}};
canvas.onpointermove=e=>{if(!drag)return;const pt=point(e);if(drag.type==='anchor')project.anchors[drag.key]=pt;else {const c=chosen(),old=drag.before.clips.find(c=>c.id===selected);c.x=Math.max(-1000,Math.min(1000,Math.round(old.x+(pt[0]-drag.pt[0])*1000)));c.y=Math.max(-600,Math.min(600,Math.round(old.y+(pt[1]-drag.pt[1])*600)));}draw();};
function finishDrag(){if(!drag)return;const next=clone(project);project=drag.before;drag=null;change(p=>Object.assign(p,next),'Position updated.');}canvas.onpointerup=finishDrag;canvas.onpointercancel=()=>{if(drag){project=drag.before;drag=null;render();}};
canvas.onkeydown=e=>{if(chosen()&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();change(p=>{const c=p.clips.find(c=>c.id===selected),n=e.shiftKey?10:1;c.x+=(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0);c.y+=(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0);});}};
$('#cues').onclick=e=>{const cue=e.target.closest('[data-cue]')?.dataset.cue;if(cue){stop();setTime(CUES[cue]*project.duration);}};
$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'Ⅱ Pause':'▶ Play';last=performance.now();if(time>=project.duration)setTime(0);};$('#scrub').oninput=e=>{stop();setTime(Number(e.target.value));};$('#back').onclick=()=>{stop();setTime(time-project.duration/project.poses.length);};$('#forward').onclick=()=>{stop();setTime(time+project.duration/project.poses.length);};
for(const id of ['direction','aura','anchors','flashes','reduced'])$('#'+id).onchange=()=>{if(id==='reduced'&&$('#reduced').checked)stop();draw();};
function tick(now){if(playing){time+=(now-last)*Number($('#speed').value);if(time>=project.duration){if($('#loop').checked)time%=project.duration;else{time=project.duration;stop();}}setTime(time);}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);
function undo(redo=false){stop();redo?stack.redo():stack.undo();project=stack.value;saveDraft();render();}$('#undo').onclick=()=>undo();$('#redo').onclick=()=>undo(true);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();undo(e.shiftKey);}});
$('#add-binding').onclick=()=>change(p=>{const id='binding.'+crypto.randomUUID();p.bindings.push({id,name:'New binding',provider:'ashenspire',kind:'card',objectId:'',event:'actionResolved',all:[],any:[],none:[],resource:'any',priority:0,enabled:true});binding=id;});$('#binding-list').onclick=e=>{if(e.target.dataset.binding){binding=e.target.dataset.binding;renderBindings();}};
$('#binding-form').onchange=e=>{const key=e.target.dataset.bindingField;if(!key)return;const v=['all','any','none'].includes(key)?tags(e.target.value):key==='priority'?Number(e.target.value):key==='enabled'?e.target.checked:e.target.value;change(p=>{p.bindings.find(b=>b.id===binding)[key]=v;});};$('#binding-form').onclick=e=>{if(e.target.id==='delete-binding')change(p=>{p.bindings=p.bindings.filter(b=>b.id!==binding);});};$('#graph').onclick=e=>{const b=e.target.closest('[data-edit-binding]');if(b){binding=b.dataset.editBinding;tab('bindings');renderBindings();}};
$('#card').innerHTML=cards.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');$('#card').value='shieldBash';function setCard(){const data=cardContext($('#card').value);$('#test-object').value=data.card.id;$('#test-tags').value=data.context.tags.map(t=>typeof t==='string'?t:t.id).join(', ');$('#test-mana').value=Number(data.card.manaCost)||0;$('#test-stamina').value=Number(data.card.staminaCost)||0;$('#test-actions').value=Number(data.card.cost)||0;testBindings();}$('#card').onchange=setCard;$('#test-form').oninput=testBindings;
$('#import-card').onclick=()=>{const {card,plan}=cardContext($('#card').value,context());if(!plan)return status('This card has no existing effect preset.');change(p=>{p.name=card.name+' · sequence';p.clips=[{...starter().clips[0],effect:plan.kind,anchor:plan.at==='target'?'target':'hand',cue:plan.projectile?'release':'contact',size:160*(plan.sizeScale||1),travel:plan.projectile}];p.bindings=[{...starter().bindings[0],objectId:card.id,all:[],name:card.name}];selected=p.clips[0].id;binding=p.bindings[0].id;});tab('compose');};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=starter(),type=b.dataset.preset;const map={shield:['Shield bash','shieldBash','shield',['shield']],ward:['Arcane ward','arcaneWard','torso',['ward','arcane']],blood:['Blood slash','bloodSlash','weapon',['blood','blade']],step:['Subtle footwork','heelScuff','feet',['dodge']],stagger:['Stagger recovery','staggerRecover','torso',['stagger']]};const [name,effect,anchor,all]=map[type];p.name=name+' · sequence';p.clips[0].effect=effect;p.clips[0].anchor=anchor;p.bindings[0].name=name;p.bindings[0].all=all;if(type==='blood'){p.bindings[0].resource='resource';p.poses=['idle','attack1','attack2','attack3','guard','idle'];}if(type==='ward')p.poses=['idle','guard','guard','guard','guard','idle'];replace(p,name+' preset opened. Undo returns to your previous work.');tab('compose');});
async function portable(){const p=clone(project);const paths=new Set(p.clips.flatMap(c=>effectFrames[c.effect]));for(const pose of p.poses)if(!Object.hasOwn(p.assets,'pose:'+pose))paths.add(PAINTED_OUTFITS[p.actor].frames[pose].file);for(const path of paths){if(p.assets[path])continue;const response=await fetch(new URL('../'+path,import.meta.url));if(!response.ok)throw Error('Cannot package '+path);const blob=await response.blob();p.assets[path]=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}p.dependencies=['ashenspire.effects','pose-studio.effects.v1'];return p;}
$('#save').onclick=async()=>{try{status('Packing referenced sprite frames…');const p=await portable(),blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=project.id.replace(/[^\w.-]/g,'_')+'.pose.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Package saved with referenced images, bindings and timeline.');}catch(e){status(e.message);}};
$('#open').onclick=()=>$('#project-file').click();$('#project-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>40000000)throw Error('Package exceeds 40 MB');const next=JSON.parse(await f.text());replace(next,'Project imported. Undo restores the previous project.');}catch(error){status('Import failed: '+error.message);}e.target.value='';};
$('#import-pose').onclick=()=>$('#pose-files').click();$('#pose-files').onchange=async e=>{try{const files=[...e.target.files];if(files.length>7)throw Error('Import at most seven images');const assets={};for(const f of files){if(!['image/png','image/webp'].includes(f.type)||f.size>4000000)throw Error('Use PNG/WebP images below 4 MB');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});const img=new Image();img.src=src;await img.decode();if(img.width>4096||img.height>4096)throw Error('Pose images must be at most 4096 × 4096');assets['pose:custom.'+crypto.randomUUID()]=src;}change(p=>{Object.assign(p.assets,assets);p.poses=Array.from({length:Math.max(5,files.length)},(_,i)=>Object.keys(assets)[Math.min(i,files.length-1)].slice(5));},'Imported poses. Position effects using the stage anchors.');}catch(error){status(error.message);}e.target.value='';};
$('#game').onclick=()=>{try{localStorage.setItem(GAME_KEY,JSON.stringify(project));window.open('../AshenSpire.html?shot=combat&shotClass='+project.actor.split('-')[0],'_blank','noopener');status('Game preview opened with these optional presentation bindings. Clear game override restores defaults.');}catch{status('Cannot store this project. Export it instead.');}};$('#clear-game').onclick=()=>{localStorage.removeItem(GAME_KEY);status('Game override cleared. Existing game tabs pick this up on their next action.');};
addEventListener('pagehide',stop);setCard();render();if(loadWarning)status(loadWarning);
