"""Encode approved Combat Studio masters for the alternative runtime."""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/design/combat-depth-2026-10-05'
OUT = ROOT / 'assets-alternative'
OUT.mkdir(exist_ok=True)
catalog = json.loads((SOURCE / 'catalog.json').read_text(encoding='utf-8'))
sprites = {}
for entry in catalog['entries']:
    if entry.get('status') != 'generated':
        continue
    image = Image.open(SOURCE / entry['file']).convert('RGBA')
    target = OUT / (entry['id'] + '.webp')
    image.save(target, 'WEBP', quality=90, method=3)
    sprites[entry['id']] = {k: entry[k] for k in ('name', 'family')}
    sprites[entry['id']].update(path='assets-alternative/' + target.name,
        size=entry['validation']['size'], bounds=entry['validation']['visibleBounds'])
layers = {}
for entry in catalog['layers'] + [{'id': 'card-section-texture', 'file': 'layers/card-section-texture.png'}]:
    target = OUT / (entry['id'] + '.webp')
    Image.open(SOURCE / entry['file']).save(target, 'WEBP', quality=90, method=3)
    layers[entry['id']] = 'assets-alternative/' + target.name
manifest = {'sprites': sprites, 'layers': layers,
    'hashes': {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(OUT.glob('*.webp'))}}
(ROOT / 'src/ui/alternativeArtCatalog.js').write_text(
    '// Generated by tools/alternative-art-build.py from approved masters.\n'
    + 'export const alternativeArtCatalog = ' + json.dumps(manifest, separators=(',', ':')) + ';\n', encoding='utf-8', newline='\n')
print(f'Encoded {len(sprites)} sprites and {len(layers)} layers.')
