"""Encode approved Combat Studio masters with the game's shared export policy."""
import hashlib
import json
import shutil
import subprocess
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/design/combat-depth-2026-10-05'
OUT = ROOT / 'assets-alternative'
catalog = json.loads((SOURCE / 'catalog.json').read_text(encoding='utf-8'))
encoder = shutil.which('cwebp')
if not encoder:
    raise SystemExit('alternative-art-build: put the libwebp cwebp encoder on PATH before exporting')

items = [(entry, 'sprite') for entry in catalog['entries'] if entry.get('status') == 'generated']
items += [(entry, 'scene') for entry in catalog['layers'] + [
    {'id': 'card-section-texture', 'file': 'layers/card-section-texture.png'}]]
requests = []
for entry, kind in items:
    source = (SOURCE / entry['file']).resolve()
    if not source.is_relative_to(SOURCE.resolve()):
        raise ValueError(f'Artwork source escapes the master directory: {source}')
    with Image.open(source) as image:
        width, height = image.size
    if kind == 'sprite' and [width, height] != entry['validation']['size']:
        raise ValueError(f"Revalidate changed master dimensions for {entry['id']}")
    requests.append({'path': ('sprites/' if kind == 'sprite' else 'environments/') + entry['id'] + '.webp',
                     'width': width, 'height': height})

# Query the JS policy once for the entire export: no copied pixel limits or
# compression constants in this Python authoring tool.
plans = json.loads(subprocess.run(
    ['node', str(ROOT / 'tools/art-export-plan.mjs')], input=json.dumps(requests),
    text=True, capture_output=True, check=True, cwd=ROOT).stdout)
OUT.mkdir(exist_ok=True)
sprites, layers, layer_sizes = {}, {}, {}
for (entry, kind), source_size, plan in zip(items, requests, plans, strict=True):
    source = SOURCE / entry['file']
    target = OUT / (entry['id'] + '.webp')
    args = [encoder, '-quiet', '-m', '6', '-q', str(plan['quality']),
            '-alpha_q', str(plan['alphaQuality']), '-alpha_filter', 'best']
    if (plan['width'], plan['height']) != (source_size['width'], source_size['height']):
        args += ['-resize', str(plan['width']), str(plan['height'])]
    subprocess.run(args + [str(source), '-o', str(target)], check=True)
    path = 'assets-alternative/' + target.name
    if kind == 'sprite':
        original_bounds = entry['validation']['visibleBounds']
        sx, sy = plan['width'] / source_size['width'], plan['height'] / source_size['height']
        bounds = [value * (sx if index % 2 == 0 else sy) for index, value in enumerate(original_bounds)]
        sprites[entry['id']] = {k: entry[k] for k in ('name', 'family')}
        sprites[entry['id']].update(path=path, size=[plan['width'], plan['height']], bounds=bounds,
            sourceSize=entry['validation']['size'], sourceBounds=original_bounds)
    else:
        layers[entry['id']] = path
        layer_sizes[entry['id']] = [plan['width'], plan['height']]

manifest = {'sprites': sprites, 'layers': layers, 'layerSizes': layer_sizes,
    'hashes': {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(OUT.glob('*.webp'))}}
(ROOT / 'src/ui/alternativeArtCatalog.js').write_text(
    '// Generated by tools/alternative-art-build.py from approved masters and the shared export policy.\n'
    + 'export const alternativeArtCatalog = ' + json.dumps(manifest, separators=(',', ':')) + ';\n',
    encoding='utf-8', newline='\n')
print(f'Encoded {len(sprites)} sprites and {len(layers)} layers; '
      f'{sum(p.stat().st_size for p in OUT.glob("*.webp")):,} bytes.')
