"""Export the reviewed idle collection; never infer animation/action anchors."""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/design/combat-depth-2026-10-05'
OUT = ROOT / 'assets-alternative'
SOURCE_COMMIT = '41ae95ae42cce66e56805cc35ae1903a92a4d5a5'
OUT.mkdir(exist_ok=True)
catalog = json.loads((SOURCE / 'catalog.json').read_text(encoding='utf-8'))
scenes = json.loads((SOURCE / 'continuation/scene-catalog.json').read_text(encoding='utf-8'))
hashes = {}
sources = {}

def encode(id, source, expected=None, sprite=False):
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    if expected and digest != expected:
        raise ValueError(f'Unreviewed source bytes: {source}')
    image = Image.open(source).convert('RGBA')
    paths = {}
    for device in ('desktop', 'phone'):
        target = OUT / (id + ('-mobile' if device == 'phone' else '') + '.webp')
        export = image.copy()
        if device == 'phone':
            limit = 768 if sprite else 1024
            export.thumbnail((limit, limit), Image.Resampling.LANCZOS)
        export.save(target, 'WEBP', quality=90 if device == 'desktop' else 82, method=3)
        # WebP's alpha is lossless, including the resized mobile alpha plane.
        decoded = Image.open(target).convert('RGBA')
        assert decoded.getchannel('A').tobytes() == export.getchannel('A').tobytes(), target
        hashes[target.name] = hashlib.sha256(target.read_bytes()).hexdigest()
        paths['path' if device == 'desktop' else 'mobilePath'] = 'assets-alternative/' + target.name
    sources[id] = {'file': source.relative_to(SOURCE).as_posix(), 'sha256': digest}
    return paths

sprites = {}
for entry in catalog['entries']:
    if entry.get('status') != 'generated':
        raise ValueError(f'Unfinished actor: {entry["id"]}')
    sprites[entry['id']] = {k: entry[k] for k in ('name', 'family', 'facing', 'pose')}
    sprites[entry['id']].update(encode(entry['id'], SOURCE / entry['file'], entry['validation']['sha256'], True),
        size=entry['validation']['size'], bounds=entry['validation']['visibleBounds'])

layers = {}
mobileLayers = {}
for entry in catalog['layers'] + [{'id': 'card-section-texture', 'file': 'layers/card-section-texture.png'}]:
    paths = encode(entry['id'], SOURCE / entry['file'])
    layers[entry['id']] = paths['path']
    mobileLayers[entry['id']] = paths['mobilePath']
sceneLayers = {}
for entry in scenes['layers']:
    sceneLayers[entry['id']] = encode('scene-' + entry['id'], SOURCE / 'continuation' / entry['file'], entry['sha256'])
    sceneLayers[entry['id']]['kind'] = entry['kind']

manifest = {'sourceCommit': SOURCE_COMMIT, 'anchorContract': 'Idle alpha bounds only; no action or hand anchors.',
    'sprites': sprites, 'layers': layers, 'mobileLayers': mobileLayers, 'sceneLayers': sceneLayers,
    'scenes': {s['id']: {k: s[k] for k in ('name', 'region', 'devices')} for s in scenes['scenes']},
    'sources': sources, 'hashes': dict(sorted(hashes.items()))}
(ROOT / 'src/ui/alternativeArtCatalog.js').write_text(
    '// Generated by tools/alternative-art-build.py from reviewed masters.\n'
    + 'export const alternativeArtCatalog = ' + json.dumps(manifest, separators=(',', ':')) + ';\n', encoding='utf-8', newline='\n')
print(f'Encoded {len(sprites)} idle actors and {len(sceneLayers)} scene layers for both devices; {len(hashes)} files.')
