// tools/content-build.mjs — compile authored JSON/CSV content into ES modules.
//
// WHY a compile step rather than fetching JSON at runtime: the game has to run
// from file:// and ship as one self-contained HTML. fetch() breaks both, and
// import assertions aren't portable enough to rely on. So content is AUTHORED
// as spreadsheet-friendly CSV (flat tables) and JSON (nested defs), and this
// compiles it into src/content/generated/*.js — plain data modules the existing
// bundler, validator and tests already understand. You edit a spreadsheet; the
// game keeps working offline with no runtime cost.
//
//   node tools/content-build.mjs            compile + report
//   node tools/content-build.mjs --check    verify generated files are current
//                                           (CI/test use — no writes)
//
// CSV rules: '#' comment lines and blank lines are skipped; the first data row
// is the header. Values are coerced — integers/floats become numbers, 'true'/
// 'false' become booleans, empty stays '', and a value containing '|' becomes
// an array. Quoted fields may contain commas.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { readdirSortedSync } from './dirorder.mjs';
import { dirname, resolve, join, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'content', 'source');
const OUT = join(ROOT, 'src', 'content', 'generated');
const CHECK = process.argv.includes('--check');

function fail(msg) {
  console.error('content-build: ' + msg);
  process.exit(1);
}

/** Split one CSV line, honouring "quoted, fields" and "" escapes. */
function splitCsvLine(line) {
  const out = [];
  let cur = '';
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (quoted) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; } else quoted = false;
      } else cur += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { out.push(cur); cur = ''; }
    else cur += ch;
  }
  out.push(cur);
  return out.map((s) => s.trim());
}

/** '12' → 12, 'true' → true, 'a|b' → ['a','b'], '' → ''. */
function coerce(raw) {
  if (raw === '') return '';
  if (raw === 'true') return true;
  if (raw === 'false') return false;
  if (raw.includes('|')) return raw.split('|').map((s) => coerce(s.trim()));
  // Only plain decimals — ids like '0E0A08' or '3d' must stay strings.
  if (/^-?\d+$/.test(raw)) return Number(raw);
  if (/^-?\d*\.\d+$/.test(raw)) return Number(raw);
  return raw;
}

function parseCsv(text, file) {
  const lines = text.split(/\r?\n/).filter((l) => l.trim() !== '' && !l.trimStart().startsWith('#'));
  if (!lines.length) fail(`${file}: no data rows`);
  const header = splitCsvLine(lines[0]);
  const dupe = header.find((h, i) => header.indexOf(h) !== i);
  if (dupe) fail(`${file}: duplicate column '${dupe}'`);
  return lines.slice(1).map((line, n) => {
    const cells = splitCsvLine(line);
    if (cells.length !== header.length) {
      fail(`${file}: row ${n + 2} has ${cells.length} cells, header has ${header.length}`);
    }
    const row = {};
    header.forEach((h, i) => { row[h] = coerce(cells[i]); });
    return row;
  });
}

// Every generated module is a plain export of one array/object, so the bundler
// and the tests treat it exactly like a hand-written content file.
function emit(name, data, sourceFile) {
  return (
    `// GENERATED by tools/content-build.mjs from content/source/${sourceFile}\n` +
    `// Do not edit by hand — edit the source file and re-run the build.\n\n` +
    `export const ${name} = ${JSON.stringify(data, null, 2)};\n`
  );
}

if (!existsSync(SRC)) fail('no content/source directory');
mkdirSync(OUT, { recursive: true });

const results = [];
let stale = 0;
for (const file of readdirSortedSync(SRC)) {
  const ext = extname(file).toLowerCase();
  if (ext !== '.csv' && ext !== '.json') continue;
  const name = basename(file, ext);
  const text = readFileSync(join(SRC, file), 'utf8');
  let data;
  if (ext === '.csv') data = parseCsv(text, file);
  else {
    try { data = JSON.parse(text); } catch (e) { fail(`${file}: ${e.message}`); }
  }
  const code = emit(name, data, file);
  const dest = join(OUT, `${name}.js`);
  const prev = existsSync(dest) ? readFileSync(dest, 'utf8') : null;
  if (prev !== code) {
    stale += 1;
    if (!CHECK) writeFileSync(dest, code);
  }
  results.push({ file, name, rows: Array.isArray(data) ? data.length : Object.keys(data).length });
}

if (CHECK && stale) {
  fail(`${stale} generated file(s) are out of date — run: node tools/content-build.mjs`);
}
console.log(CHECK ? 'content-build: generated files are current' : 'content-build: OK');
for (const r of results) console.log(`  ${r.file.padEnd(16)} → src/content/generated/${r.name}.js  (${r.rows} rows)`);
